## Minería de Datos. Análisis De La Logística Portuaria en 2024

In [2]:
# Import Packages
import pandas as pd
import numpy as np
import seaborn as sns
import os 
import openpyxl

In [3]:
#Lectura del fichero
ruta = os.path.join('C:/Users/Encarni/Desktop/TFM/Tablas_descargadas/Modificados_pestaña/2024/1_enero_2024.xlsx')
df_enero = pd.read_excel(ruta)
display(df_enero)

,Autoridad Portuaria,Enero Graneles Líquidos,Unnamed: 2,Acumulado desde Enero Graneles Líquidos,Unnamed: 4,Unnamed: 5,Enero Graneles Sólidos,Unnamed: 7,Acumulado desde Enero Graneles Sólidos,Unnamed: 9,...,Enero Automóviles en régimen de pasaje (Unidades),Unnamed: 112,Acumulado desde Enero Automóviles en régimen de pasaje (Unidades),Unnamed: 114,Unnamed: 115,Enero Automóviles en régimen de mercancía (Unidades),Unnamed: 117,Acumulado desde Enero Automóviles en régimen de mercancía (Unidades),Unnamed: 119,Unnamed: 120
0,NaN,2023 t,2024 t,2023 t,2024 t,Var. (%),2023 t,2024 t,2023 t,2024 t,...,2023,2024,2023,2024,Var. (%),2023,2024,2023,2024,Var. (%)
1,A Coruña,676655,719906,676655,719906,6.391884,521447,406133,521447,406133,...,0,0,0,0,,0,0,0,0,
2,Alicante,5453,9007,5453,9007,65.175133,191759,109123,191759,109123,...,2517,1580,2517,1580,-37.226857,78,51,78,51,-34.615385
3,Almería,4538,18511,4538,18511,307.910974,299084,256126,299084,256126,...,9707,11445,9707,11445,17.904605,170,239,170,239,40.588235
4,Avilés,55417,61421,55417,61421,10.834221,271758,234074,271758,234074,...,0,0,0,0,,0,0,0,0,
5,Bahía de Algeciras,2380167,2793935,2380167,2793935,17.38399,31659,42904,31659,42904,...,66691,81135,66691,81135,21.658095,235,327,235,327,39.148936
6,Bahía de Cádiz,163563,18934,163563,18934,-88.424032,137032,206223,137032,206223,...,1078,1102,1078,1102,2.226345,1314,1224,1314,1224,-6.849315
7,Baleares,71491,102646,71491,102646,43.578912,43279,22156,43279,22156,...,53451,54605,53451,54605,2.158987,5525,7841,5525,7841,41.918552
8,Barcelona,989889,766073,989889,766073,-22.610212,413626,324206,413626,324206,...,21954,22448,21954,22448,2.250159,47534,49721,47534,49721,4.600917
9,Bilbao,1503473,2134486,1503473,2134486,41.970358,334672,280264,334672,280264,...,1088,0,1088,0,-100,1530,2377,1530,2377,55.359477
10,Cartagena,2345886,2137657,2345886,2137657,-8.876348,870622,878956,870622,878956,...,0,0,0,0,,11,0,11,0,-100
11,Castellón,672781,607958,672781,607958,-9.635082,637990,374630,637990,374630,...,0,0,0,0,,83,29,83,29,-65.060241
12,Ceuta,51759,72593,51759,72593,40.251937,1400,0,1400,0,...,32603,33936,32603,33936,4.088581,118,171,118,171,44.915254
13,Ferrol-San Cibrao,458282,177899,458282,177899,-61.181325,249197,383943,249197,383943,...,0,0,0,0,,22,0,22,0,-100
14,Gijón,92447,169258,92447,169258,83.086525,1378370,1021870,1378370,1021870,...,0,0,0,0,,0,0,0,0,
15,Huelva,2131411,2309681,2131411,2309681,8.363943,556185,554276,556185,554276,...,2664,2628,2664,2628,-1.351351,709,729,709,729,2.820874
16,Las Palmas,642064,745624,642064,745624,16.129233,31252,28101,31252,28101,...,44058,44902,44058,44902,1.915657,25384,28255,25384,28255,11.310274
17,Málaga,2010,9625,2010,9625,378.855721,160617,211039,160617,211039,...,4532,5466,4532,5466,20.609003,1304,4599,1304,4599,252.684049
18,Marín y Ría de Pontevedra,0,0,0,0,,116767,217105,116767,217105,...,0,0,0,0,,5,16,5,16,220
19,Melilla,3749,6208,3749,6208,65.590824,1499,0,1499,0,...,8143,10120,8143,10120,24.278521,158,227,158,227,43.670886
20,Motril,85635,146166,85635,146166,70.684884,26234,63942,26234,63942,...,1234,2546,1234,2546,106.320908,1011,1,1011,1,-99.901088
21,Pasaia,0,0,0,0,,60947,74223,60947,74223,...,0,0,0,0,,18248,19555,18248,19555,7.162429
22,Santa Cruz de Tenerife,345086,342184,345086,342184,-0.84095,29549,12828,29549,12828,...,119666,123443,119666,123443,3.156285,5839,6530,5839,6530,11.834218
23,Santander,13725,19805,13725,19805,44.298725,336932,394355,336932,394355,...,3922,5121,3922,5121,30.571137,33240,20335,33240,20335,-38.823706
24,Sevilla,32286,61191,32286,61191,89.527969,158632,196999,158632,196999,...,0,0,0,0,,258,944,258,944,265.891473
25,Tarragona,1526567,1938824,1526567,1938824,27.005497,1063474,996005,1063474,996005,...,0,0,0,0,,23693,27293,23693,27293,15.194361
26,Valencia,512904,339077,512904,339077,-33.890748,189304,242688,189304,242688,...,13720,15562,13720,15562,13.425656,49254,50909,49254,50909,3.360133
27,Vigo,2993,0,2993,0,-100,30628,15432,30628,15432,...,0,0,0,0,,46861,55801,46861,55801,19.077698
28,Vilagarcía,15946,8000,15946,8000,-49.830679,35816,24702,35816,24702,...,0,0,0,0,,10,5,10,5,-50
29,TOTAL,14786177,15716669,14786177,15716669,6.292986,8179731,7572303,8179731,7572303,...,387028,416039,387028,416039,7.49584,262594,277179,262594,277179,5.554202

In [4]:
Renombrar_enero = {'Enero Graneles Líquidos': 'Enero_2023 t Graneles Líquidos', 'Unnamed: 2': 'Enero_2024 t Graneles Líquidos',
             'Enero Graneles Sólidos': 'Enero_2023 t Graneles Sólidos', 'Unnamed: 7': 'Enero_2024 t Graneles Sólidos',
             'Enero Mercancía General': 'Enero_2023 t Mercancía General', 'Unnamed: 12': 'Enero_2024 t Mercancía General',
             'Enero Mercancía general en contenedores': 'Enero_2023 t Mercancía General Contenedores', 'Unnamed: 17': 'Enero_2024 t Mercancía General Contenedores',
             'Enero Pesca': 'Enero_2023 t Pesca', 'Unnamed: 22': 'Enero_2024 t Pesca',
             'Enero Avituallamiento': 'Enero_2023 t Avituallamiento', 'Unnamed: 27': 'Enero_2024 t Avituallamiento',
             'Enero Avituallamiento de combustibles líquidos': 'Enero_2023 t Avituallamiento De Combustibles Líquidos', 'Unnamed: 32': 'Enero_2024 t Avituallamiento De Combustibles Líquidos',
             'Enero Tráfico interior': 'Enero_2023 t Tráfico Interior', 'Unnamed: 37': 'Enero_2024 t Tráfico Interior',
             'Enero Mercancías en tránsito': 'Enero_2023 t Mercancías En Tránsito', 'Unnamed: 42': 'Enero_2024 t Mercancías En Tránsito',
             'Enero Mercancías en tránsito en contenedores': 'Enero_2023 t Mercancías En Tránsito En Contenedores', 'Unnamed: 47': 'Enero_2024 t Mercancías En Tránsito En Contenedores',
             'Enero Tráfico Ro-Ro': 'Enero_2023 t Tráfico Ro-Ro', 'Unnamed: 52': 'Enero_2024 t Tráfico Ro-Ro',
             'Enero Unidades de transporte intermodal Ro-Ro UTIS': 'Enero_2023 UTIS Ro-Ro', 'Unnamed: 57': 'Enero_2024 UTIS Ro-Ro', 
             'Enero Contenedores TEUS': 'Enero_2023 TEUS Contenedores', 'Unnamed: 62': 'Enero_2024 TEUS Contenedores', 
             'Enero Contenedores en tránsito TEUS': 'Enero_2023 TEUS Contenedores En Tránsito', 'Unnamed: 67': 'Enero_2024 TEUS Contenedores En Tránsito',
             'Enero Contenedores entrada-salida nacional TEUS': 'Enero_2023 TEUS Contenedores Entrada-Salida Nacional', 'Unnamed: 72': 'Enero_2024 TEUS Contenedores Entrada-Salida Nacional',
             'Enero Contenedores entrada-salida exterior TEUS': 'Enero_2023 TEUS Contenedores Entrada-Salida Exterior', 'Unnamed: 77': 'Enero_2024 TEUS Contenedores Entrada-Salida Exterior',
             'Enero Buques mercantes (Número)': 'Enero_2023 Unidades Buques Mercantes', 'Unnamed: 82': 'Enero_2024 Unidades Buques Mercantes', 
             'Enero Buques mercantes (G.T.)': 'Enero_2023 G.T. Buques Mercantes', 'Unnamed: 87': 'Enero_2024 G.T. Buques Mercantes',
             'Enero Buques de crucero (Número)': 'Enero_2023 Unidades Buques De Crucero', 'Unnamed: 92': 'Enero_2024 Unidades Buques De Crucero',
             'Enero Pasajeros en régimen de transporte y de crucero (Número)': 'Enero_2023 Pasajeros En Régimen De Transporte Y De Crucero', 'Unnamed: 97': 'Enero_2024 Pasajeros En Régimen De Transporte Y De Crucero',
             'Enero Pasajeros en régimen de transporte (Número)': 'Enero_2023 Pasajeros En Régimen De Transporte', 'Unnamed: 102': 'Enero_2024 Pasajeros En Régimen De Transporte',
             'Enero Pasajeros de crucero (Número)': 'Enero_2023 Pasajeros De Crucero', 'Unnamed: 107': 'Enero_2024 Pasajeros De Crucero',
             'Enero Automóviles en régimen de pasaje (Unidades)': 'Enero_2023 Automóviles En Régimen De Pasaje', 'Unnamed: 112': 'Enero_2024 Automóviles En Régimen De Pasaje',
             'Enero Automóviles en régimen de mercancía (Unidades)': 'Enero_2023 Automóviles En Régimen De Mercancía', 'Unnamed: 117': 'Enero_2024 Automóviles En Régimen De Mercancía'}

In [5]:
df_enero = df_enero.drop(['Acumulado desde Enero Graneles Líquidos', 'Unnamed: 4', 'Unnamed: 5' ], axis=1)
df_enero = df_enero.drop(['Acumulado desde Enero Graneles Sólidos', 'Unnamed: 9', 'Unnamed: 10'], axis=1)
df_enero = df_enero.drop(['Acumulado desde Enero Mercancía General', 'Unnamed: 14', 'Unnamed: 15'], axis=1)
df_enero = df_enero.drop(['Acumulado desde Enero Mercancía General en contenedores', 'Unnamed: 19', 'Unnamed: 20'], axis=1)
df_enero = df_enero.drop(['Acumulado desde Enero Pesca', 'Unnamed: 24', 'Unnamed: 25'], axis=1)
df_enero = df_enero.drop(['Acumulado desde Enero Avituallamiento', 'Unnamed: 29', 'Unnamed: 30'], axis=1)
df_enero = df_enero.drop(['Acumulado desde Enero Avituallamiento de combustibles líquidos', 'Unnamed: 34', 'Unnamed: 35'], axis=1)
df_enero = df_enero.drop(['Acumulado desde Enero Tráfico interior', 'Unnamed: 39', 'Unnamed: 40'], axis=1)
df_enero = df_enero.drop(['Acumulado desde Enero Mercancías en tránsito', 'Unnamed: 44', 'Unnamed: 45'], axis=1)
df_enero = df_enero.drop(['Acumulado desde Enero Mercancías en tránsito en contenedores', 'Unnamed: 49', 'Unnamed: 50'], axis=1)
df_enero = df_enero.drop(['Acumulado desde Enero Tráfico Ro-Ro', 'Unnamed: 54', 'Unnamed: 55'], axis=1)
df_enero = df_enero.drop(['Acumulado desde Enero Unidades de transporte intermodal Ro-Ro UTIS', 'Unnamed: 59', 'Unnamed: 60'], axis=1)
df_enero = df_enero.drop(['Acumulado desde Enero Contenedores TEUS', 'Unnamed: 64', 'Unnamed: 65'], axis=1)
df_enero = df_enero.drop(['Acumulado desde Enero Contenedores en tránsito TEUS', 'Unnamed: 69', 'Unnamed: 70'], axis=1)
df_enero = df_enero.drop(['Acumulado desde Enero Contenedores entrada-salida nacional TEUS', 'Unnamed: 74', 'Unnamed: 75'], axis=1)
df_enero = df_enero.drop(['Acumulado desde Enero Contenedores entrada-salida exterior TEUS', 'Unnamed: 79', 'Unnamed: 80'], axis=1)
df_enero = df_enero.drop(['Acumulado desde Enero Buques mercantes (Número)', 'Unnamed: 84', 'Unnamed: 85'], axis=1)
df_enero = df_enero.drop(['Acumulado desde Enero Buques mercantes (G.T.)', 'Unnamed: 89', 'Unnamed: 90'], axis=1)
df_enero = df_enero.drop(['Acumulado desde Enero Buques de crucero (Número)', 'Unnamed: 94', 'Unnamed: 95'], axis=1)
df_enero = df_enero.drop(['Acumulado desde Enero Pasajeros en régimen de transporte y de crucero (Número)', 'Unnamed: 99', 'Unnamed: 100'], axis=1)
df_enero = df_enero.drop(['Acumulado desde Enero Pasajeros en régimen de transporte (Número)', 'Unnamed: 104', 'Unnamed: 105'], axis=1)
df_enero = df_enero.drop(['Acumulado desde Enero Pasajeros de crucero (Número)', 'Unnamed: 109', 'Unnamed: 110'], axis=1)
df_enero = df_enero.drop(['Acumulado desde Enero Automóviles en régimen de pasaje (Unidades)', 'Unnamed: 114', 'Unnamed: 115'], axis=1)
df_enero = df_enero.drop(['Acumulado desde Enero Automóviles en régimen de mercancía (Unidades)', 'Unnamed: 119', 'Unnamed: 120'], axis=1)

In [6]:
df_enero = df_enero.rename(columns=Renombrar_enero)

In [7]:
# Eliminación de la primera fila. Axis=0, eje filas.
df_enero = df_enero.drop(0, axis=0)

In [8]:
df_enero.columns

Index(['Autoridad Portuaria', 'Enero_2023 t Graneles Líquidos',
       'Enero_2024 t Graneles Líquidos', 'Enero_2023 t Graneles Sólidos',
       'Enero_2024 t Graneles Sólidos', 'Enero_2023 t Mercancía General',
       'Enero_2024 t Mercancía General',
       'Enero_2023 t Mercancía General Contenedores',
       'Enero_2024 t Mercancía General Contenedores', 'Enero_2023 t Pesca',
       'Enero_2024 t Pesca', 'Enero_2023 t Avituallamiento',
       'Enero_2024 t Avituallamiento',
       'Enero_2023 t Avituallamiento De Combustibles Líquidos',
       'Enero_2024 t Avituallamiento De Combustibles Líquidos',
       'Enero_2023 t Tráfico Interior', 'Enero_2024 t Tráfico Interior',
       'Enero_2023 t Mercancías En Tránsito',
       'Enero_2024 t Mercancías En Tránsito',
       'Enero_2023 t Mercancías En Tránsito En Contenedores',
       'Enero_2024 t Mercancías En Tránsito En Contenedores',
       'Enero_2023 t Tráfico Ro-Ro', 'Enero_2024 t Tráfico Ro-Ro',
       'Enero_2023 UTIS Ro-Ro', 'Enero_2024 UTIS Ro-Ro',
       'Enero_2023 TEUS Contenedores', 'Enero_2024 TEUS Contenedores',
       'Enero_2023 TEUS Contenedores En Tránsito',
       'Enero_2024 TEUS Contenedores En Tránsito',
       'Enero_2023 TEUS Contenedores Entrada-Salida Nacional',
       'Enero_2024 TEUS Contenedores Entrada-Salida Nacional',
       'Enero_2023 TEUS Contenedores Entrada-Salida Exterior',
       'Enero_2024 TEUS Contenedores Entrada-Salida Exterior',
       'Enero_2023 Unidades Buques Mercantes',
       'Enero_2024 Unidades Buques Mercantes',
       'Enero_2023 G.T. Buques Mercantes', 'Enero_2024 G.T. Buques Mercantes',
       'Enero_2023 Unidades Buques De Crucero',
       'Enero_2024 Unidades Buques De Crucero',
       'Enero_2023 Pasajeros En Régimen De Transporte Y De Crucero',
       'Enero_2024 Pasajeros En Régimen De Transporte Y De Crucero',
       'Enero_2023 Pasajeros En Régimen De Transporte',
       'Enero_2024 Pasajeros En Régimen De Transporte',
       'Enero_2023 Pasajeros De Crucero', 'Enero_2024 Pasajeros De Crucero',
       'Enero_2023 Automóviles En Régimen De Pasaje',
       'Enero_2024 Automóviles En Régimen De Pasaje',
       'Enero_2023 Automóviles En Régimen De Mercancía',
       'Enero_2024 Automóviles En Régimen De Mercancía'],
      dtype='object')

In [9]:
df_enero.head(2)

,Autoridad Portuaria,Enero_2023 t Graneles Líquidos,Enero_2024 t Graneles Líquidos,Enero_2023 t Graneles Sólidos,Enero_2024 t Graneles Sólidos,Enero_2023 t Mercancía General,Enero_2024 t Mercancía General,Enero_2023 t Mercancía General Contenedores,Enero_2024 t Mercancía General Contenedores,Enero_2023 t Pesca,...,Enero_2023 Pasajeros En Régimen De Transporte Y De Crucero,Enero_2024 Pasajeros En Régimen De Transporte Y De Crucero,Enero_2023 Pasajeros En Régimen De Transporte,Enero_2024 Pasajeros En Régimen De Transporte,Enero_2023 Pasajeros De Crucero,Enero_2024 Pasajeros De Crucero,Enero_2023 Automóviles En Régimen De Pasaje,Enero_2024 Automóviles En Régimen De Pasaje,Enero_2023 Automóviles En Régimen De Mercancía,Enero_2024 Automóviles En Régimen De Mercancía
1,A Coruña,676655,719906,521447,406133,40997,29789,66,0,1202.998,...,6584,9704,0,0,6584,9704,0,0,0,0
2,Alicante,5453,9007,191759,109123,96205,86149,89346,77281,0,...,20175,8151,9362,5990,10813,2161,2517,1580,78,51

## Febrero

In [10]:
ruta_febrero = os.path.join('C:/Users/Encarni/Desktop/TFM/Tablas_descargadas/Modificados_pestaña/2024/2_febrero_2024.xlsx')
df_febrero = pd.read_excel(ruta_febrero)
display(df_febrero)

,Autoridad Portuaria,Febrero Graneles Líquidos,Unnamed: 2,Acumulado desde Febrero Graneles Líquidos,Unnamed: 4,Unnamed: 5,Febrero Graneles Sólidos,Unnamed: 7,Acumulado desde Febrero Graneles Sólidos,Unnamed: 9,...,Febrero Automóviles en régimen de pasaje (Unidades),Unnamed: 112,Acumulado desde Febrero Automóviles en régimen de pasaje (Unidades),Unnamed: 114,Unnamed: 115,Febrero Automóviles en régimen de mercancía (Unidades),Unnamed: 117,Acumulado desde Febrero Automóviles en régimen de mercancía (Unidades),Unnamed: 119,Unnamed: 120
0,NaN,2023 t,2024 t,2023 t,2024 t,Var. (%),2023 t,2024 t,2023 t,2024 t,...,2023,2024,2023,2024,Var. (%),2023,2024,2023,2024,Var. (%)
1,A Coruña,895370,747204,1572025,1467110,-6.673876,542383,288615,1063830,694748,...,0,0,0,0,,0,0,0,0,
2,Alicante,0,1848,5453,10855,99.064735,135408,175579,327167,284702,...,1938,4102,4455,5682,27.542088,142,241,220,292,32.727273
3,Almería,3689,19338,8227,37849,360.058344,313763,256103,612847,512229,...,6871,8314,16578,19759,19.188081,152,230,322,469,45.652174
4,Avilés,72394,29158,127811,90579,-29.130513,223174,168150,494932,402224,...,0,0,0,0,,0,0,0,0,
5,Bahía de Algeciras,1898017,2444604,4278184,5238539,22.447725,35205,23432,66864,66336,...,49402,62103,116093,143238,23.382116,243,336,478,663,38.702929
6,Bahía de Cádiz,148050,22127,311613,41061,-86.823079,162994,144490,300026,350713,...,846,917,1924,2019,4.93763,2377,1759,3691,2983,-19.181794
7,Baleares,81764,79818,153255,182464,19.059085,41212,41626,84491,63782,...,43672,54264,97123,108869,12.093943,6570,11032,12095,18873,56.039686
8,Barcelona,1070862,1012582,2060751,1778655,-13.68899,369020,362565,782646,686771,...,17067,18146,39021,40594,4.031163,72364,60872,119898,110593,-7.760763
9,Bilbao,1505199,1467586,3008672,3602072,19.722987,278019,264448,612691,544712,...,804,0,1892,0,-100,3086,1327,4616,3704,-19.757366
10,Cartagena,2106262,2638793,4452148,4776450,7.284169,557493,740289,1428115,1619245,...,0,0,0,0,,0,4,11,4,-63.636364
11,Castellón,732854,769242,1405635,1377200,-2.022929,406445,455495,1044435,830125,...,0,0,0,0,,96,26,179,55,-69.273743
12,Ceuta,49966,19340,101725,91933,-9.625952,1000,0,2400,0,...,22761,27699,55364,61635,11.326855,105,118,223,289,29.596413
13,Ferrol-San Cibrao,477001,114330,935283,292229,-68.755019,296746,275642,545943,659585,...,0,0,0,0,,0,0,22,0,-100
14,Gijón,94982,80140,187429,249398,33.062653,1402222,873332,2780592,1895202,...,0,0,0,0,,1,3,1,3,200
15,Huelva,2211222,1819801,4342633,4129482,-4.908336,414719,287063,970904,841339,...,2392,2148,5056,4776,-5.537975,878,1726,1587,2455,54.694392
16,Las Palmas,561677,604892,1203741,1350516,12.193238,22533,21187,53785,49288,...,42114,43458,86172,88360,2.539108,21116,40167,46500,68422,47.144086
17,Málaga,12900,0,14910,9625,-35.446009,71662,87694,232279,298733,...,2745,3533,7277,8999,23.663598,4577,21298,5881,25897,340.350281
18,Marín y Ría de Pontevedra,0,0,0,0,,51001,19990,167768,237095,...,0,0,0,0,,3,146,8,162,1925
19,Melilla,5796,6750,9545,12958,35.756941,0,0,1499,0,...,5017,7194,13160,17314,31.56535,201,10922,359,11149,3005.571031
20,Motril,138237,97889,223872,244055,9.01542,23885,99620,50119,163562,...,506,1809,1740,4355,150.287356,3,9,1014,10,-99.013807
21,Pasaia,0,0,0,0,,65312,57750,126259,131973,...,0,0,0,0,,22488,23593,40736,43148,5.921053
22,Santa Cruz de Tenerife,339305,325359,684391,667543,-2.461751,10829,29080,40378,41908,...,125480,134453,245146,257896,5.200982,6325,6900,12164,13430,10.407761
23,Santander,28078,14463,41803,34268,-18.025022,258750,234434,595682,628789,...,3622,4736,7544,9857,30.660127,47000,31260,80240,51595,-35.699153
24,Sevilla,35006,36541,67292,97732,45.235689,148593,157202,307225,354201,...,0,0,0,0,,312,365,570,1309,129.649123
25,Tarragona,1781068,1455820,3307635,3394644,2.63055,1049845,738658,2113319,1734663,...,0,0,0,0,,14764,11893,38457,39186,1.895624
26,Valencia,324071,353051,836975,692128,-17.306013,115459,295743,304763,538431,...,8489,10745,22209,26307,18.451979,53053,37957,102307,88866,-13.137908
27,Vigo,5744,6006,8737,6006,-31.257869,27030,15951,57658,31383,...,0,0,0,0,,45072,66274,91933,122075,32.786921
28,Vilagarcía,35868,20404,51814,28404,-45.180839,29220,18032,65036,42734,...,0,0,0,0,,7,11,17,16,-5.882353
29,TOTAL,14615382,14187086,29401559,29903755,1.708059,7053922,6132170,15233653,13704473,...,333726,383621,720754,799660,10.947702,300935,328469,563529,605648,7.47415

In [11]:
df_febrero.columns

Index(['Autoridad Portuaria', 'Febrero Graneles Líquidos', 'Unnamed: 2',
       'Acumulado desde Febrero Graneles Líquidos', 'Unnamed: 4', 'Unnamed: 5',
       'Febrero Graneles Sólidos', 'Unnamed: 7',
       'Acumulado desde Febrero Graneles Sólidos', 'Unnamed: 9',
       ...
       'Febrero Automóviles en régimen de pasaje (Unidades)', 'Unnamed: 112',
       'Acumulado desde Febrero Automóviles en régimen de pasaje (Unidades)',
       'Unnamed: 114', 'Unnamed: 115',
       'Febrero Automóviles en régimen de mercancía (Unidades)',
       'Unnamed: 117',
       'Acumulado desde Febrero Automóviles en régimen de mercancía (Unidades)',
       'Unnamed: 119', 'Unnamed: 120'],
      dtype='object', length=121)

In [12]:
df_febrero = df_febrero.drop(['Acumulado desde Febrero Graneles Líquidos', 'Unnamed: 4', 'Unnamed: 5' ], axis=1)
df_febrero = df_febrero.drop(['Acumulado desde Febrero Graneles Sólidos', 'Unnamed: 9', 'Unnamed: 10'], axis=1)
df_febrero = df_febrero.drop(['Acumulado desde Febrero Mercancía General', 'Unnamed: 14', 'Unnamed: 15'], axis=1)
df_febrero = df_febrero.drop(['Acumulado desde Febrero Mercancía General en contenedores', 'Unnamed: 19', 'Unnamed: 20'], axis=1)
df_febrero = df_febrero.drop(['Acumulado desde Febrero Pesca', 'Unnamed: 24', 'Unnamed: 25'], axis=1)
df_febrero = df_febrero.drop(['Acumulado desde Febrero Avituallamiento', 'Unnamed: 29', 'Unnamed: 30'], axis=1)
df_febrero = df_febrero.drop(['Acumulado desde Febrero Avituallamiento de combustibles líquidos', 'Unnamed: 34', 'Unnamed: 35'], axis=1)
df_febrero = df_febrero.drop(['Acumulado desde Febrero Tráfico interior', 'Unnamed: 39', 'Unnamed: 40'], axis=1)
df_febrero = df_febrero.drop(['Acumulado desde Febrero Mercancías en tránsito', 'Unnamed: 44', 'Unnamed: 45'], axis=1)
df_febrero = df_febrero.drop(['Acumulado desde Febrero Mercancías en tránsito en contenedores', 'Unnamed: 49', 'Unnamed: 50'], axis=1)
df_febrero = df_febrero.drop(['Acumulado desde Febrero Tráfico Ro-Ro', 'Unnamed: 54', 'Unnamed: 55'], axis=1)
df_febrero = df_febrero.drop(['Acumulado desde Febrero Unidades de transporte intermodal Ro-Ro UTIS', 'Unnamed: 59', 'Unnamed: 60'], axis=1)
df_febrero = df_febrero.drop(['Acumulado desde Febrero Contenedores TEUS', 'Unnamed: 64', 'Unnamed: 65'], axis=1)
df_febrero = df_febrero.drop(['Acumulado desde Febrero Contenedores en tránsito TEUS', 'Unnamed: 69', 'Unnamed: 70'], axis=1)
df_febrero = df_febrero.drop(['Acumulado desde Febrero Contenedores entrada-salida nacional TEUS', 'Unnamed: 74', 'Unnamed: 75'], axis=1)
df_febrero = df_febrero.drop(['Acumulado desde Febrero Contenedores entrada-salida exterior TEUS', 'Unnamed: 79', 'Unnamed: 80'], axis=1)
df_febrero = df_febrero.drop(['Acumulado desde Febrero Buques mercantes (Número)', 'Unnamed: 84', 'Unnamed: 85'], axis=1)
df_febrero = df_febrero.drop(['Acumulado desde Febrero Buques mercantes (G.T.)', 'Unnamed: 89', 'Unnamed: 90'], axis=1)
df_febrero = df_febrero.drop(['Acumulado desde Febrero Buques de crucero (Número)', 'Unnamed: 94', 'Unnamed: 95'], axis=1)
df_febrero = df_febrero.drop(['Acumulado desde Febrero Pasajeros en régimen de transporte y de crucero (Número)', 'Unnamed: 99', 'Unnamed: 100'], axis=1)
df_febrero = df_febrero.drop(['Acumulado desde Febrero Pasajeros en régimen de transporte (Número)', 'Unnamed: 104', 'Unnamed: 105'], axis=1)
df_febrero = df_febrero.drop(['Acumulado desde Febrero Pasajeros de crucero (Número)', 'Unnamed: 109', 'Unnamed: 110'], axis=1)
df_febrero = df_febrero.drop(['Acumulado desde Febrero Automóviles en régimen de pasaje (Unidades)', 'Unnamed: 114', 'Unnamed: 115'], axis=1)
df_febrero = df_febrero.drop(['Acumulado desde Febrero Automóviles en régimen de mercancía (Unidades)', 'Unnamed: 119', 'Unnamed: 120'], axis=1)

In [13]:
df_febrero.head(10)

,Autoridad Portuaria,Febrero Graneles Líquidos,Unnamed: 2,Febrero Graneles Sólidos,Unnamed: 7,Febrero Mercancía General,Unnamed: 12,Febrero Mercancía general en contenedores,Unnamed: 17,Febrero Pesca,...,Febrero Pasajeros en régimen de transporte y de crucero (Número),Unnamed: 97,Febrero Pasajeros en régimen de transporte (Número),Unnamed: 102,Febrero Pasajeros de crucero (Número),Unnamed: 107,Febrero Automóviles en régimen de pasaje (Unidades),Unnamed: 112,Febrero Automóviles en régimen de mercancía (Unidades),Unnamed: 117
0,NaN,2023 t,2024 t,2023 t,2024 t,2023 t,2024 t,2023 t,2024 t,2023 t,...,2023,2024,2023,2024,2023,2024,2023,2024,2023,2024
1,A Coruña,895370,747204,542383,288615,57323,14295,0,0,1385.374,...,0,3714,0,0,0,3714,0,0,0,0
2,Alicante,0,1848,135408,175579,96732,92710,89634,89152,0,...,18333,11828,8555,11828,9778,0,1938,4102,142,241
3,Almería,3689,19338,313763,256103,97314,116222,9285,18881,145.575,...,22979,27115,22979,27115,0,0,6871,8314,152,230
4,Avilés,72394,29158,223174,168150,83122,70654,0,0,634.812,...,0,0,0,0,0,0,0,0,0,0
5,Bahía de Algeciras,1898017,2444604,35205,23432,5293601,5828377,4055921,4746479,26.18,...,237169,290981,237169,290981,0,0,49402,62103,243,336
6,Bahía de Cádiz,148050,22127,162994,144490,155382,176729,108758,124104,703.2,...,20845,12721,1426,1510,19419,11211,846,917,2377,1759
7,Baleares,81764,79818,41212,41626,993895,1105893,23743,25170,102.359,...,266579,292439,220283,247122,46296,45317,43672,54264,6570,11032
8,Barcelona,1070862,1012582,369020,362565,3354053,4046216,2522048,3148202,106.389,...,135929,132848,56735,57909,79194,74939,17067,18146,72364,60872
9,Bilbao,1505199,1467586,278019,264448,632124,558084,444749,377957,0,...,2208,36,2208,36,0,0,804,0,3086,1327

In [14]:
df_febrero = df_febrero.drop(0, axis=0)

In [15]:
Renombrar_febrero = {'Febrero Graneles Líquidos': 'Febrero_2023 t Graneles Líquidos', 'Unnamed: 2': 'Febrero_2024 t Graneles Líquidos',
             'Febrero Graneles Sólidos': 'Febrero_2023 t Graneles Sólidos', 'Unnamed: 7': 'Febrero_2024 t Graneles Sólidos',
             'Febrero Mercancía General ': 'Febrero_2023 t Mercancía General', 'Unnamed: 12': 'Febrero_2024 t Mercancía General',
             'Febrero Mercancía general en contenedores': 'Febrero_2023 t Mercancía General Contenedores', 'Unnamed: 17': 'Febrero_2024 t Mercancía General Contenedores',
             'Febrero Pesca': 'Febrero_2023 t Pesca', 'Unnamed: 22': 'Febrero_2024 t Pesca',
             'Febrero Avituallamiento': 'Febrero_2023 t Avituallamiento', 'Unnamed: 27': 'Febrero_2024 t Avituallamiento',
             'Febrero Avituallamiento de combustibles líquidos': 'Febrero_2023 t Avituallamiento De Combustibles Líquidos', 'Unnamed: 32': 'Febrero_2024 t Avituallamiento De Combustibles Líquidos',
             'Febrero Tráfico interior': 'Febrero_2023 t Tráfico Interior', 'Unnamed: 37': 'Febrero_2024 t Tráfico Interior',
             'Febrero Mercancías en tránsito': 'Febrero_2023 t Mercancías En Tránsito', 'Unnamed: 42': 'Febrero_2024 t Mercancías En Tránsito',
             'Febrero Mercancías en tránsito en contenedores': 'Febrero_2023 t Mercancías En Tránsito En Contenedores', 'Unnamed: 47': 'Febrero_2024 t Mercancías En Tránsito En Contenedores',
             'Febrero Tráfico Ro-Ro': 'Febrero_2023 t Tráfico Ro-Ro', 'Unnamed: 52': 'Febrero_2024 t Tráfico Ro-Ro',
             'Febrero Unidades de transporte intermodal Ro-Ro  UTIS': 'Febrero_2023 UTIS Ro-Ro', 'Unnamed: 57': 'Febrero_2024 UTIS Ro-Ro', 
             'Febrero Contenedores TEUS': 'Febrero_2023 TEUS Contenedores', 'Unnamed: 62': 'Febrero_2024 TEUS Contenedores', 
             'Febrero Contenedores en tránsito TEUS': 'Febrero_2023 TEUS Contenedores En Tránsito', 'Unnamed: 67': 'Febrero_2024 TEUS Contenedores En Tránsito',
             'Febrero Contenedores entrada-salida nacional TEUS': 'Febrero_2023 TEUS Contenedores Entrada-Salida Nacional', 'Unnamed: 72': 'Febrero_2024 TEUS Contenedores Entrada-Salida Nacional',
             'Febrero Contenedores entrada-salida exterior TEUS': 'Febrero_2023 TEUS Contenedores Entrada-Salida Exterior', 'Unnamed: 77': 'Febrero_2024 TEUS Contenedores Entrada-Salida Exterior',
             'Febrero Buques mercantes (Número)': 'Febrero_2023 Unidades Buques Mercantes', 'Unnamed: 82': 'Febrero_2024 Unidades Buques Mercantes', 
             'Febrero Buques mercantes (G.T.)': 'Febrero_2023 G.T. Buques Mercantes', 'Unnamed: 87': 'Febrero_2024 G.T. Buques Mercantes',
             'Febrero Buques de crucero (Número)': 'Febrero_2023 Unidades Buques De Crucero', 'Unnamed: 92': 'Febrero_2024 Unidades Buques De Crucero',
             'Febrero Pasajeros en régimen de transporte y de crucero (Número)': 'Febrero_2023 Pasajeros En Régimen De Transporte Y De Crucero', 'Unnamed: 97': 'Febrero_2024 Pasajeros En Régimen De Transporte Y De Crucero',
             'Febrero Pasajeros en régimen de transporte (Número)': 'Febrero_2023 Pasajeros En Régimen De Transporte', 'Unnamed: 102': 'Febrero_2024 Pasajeros En Régimen De Transporte',
             'Febrero Pasajeros de crucero (Número)': 'Febrero_2023 Pasajeros De Crucero', 'Unnamed: 107': 'Febrero_2024 Pasajeros De Crucero',
             'Febrero Automóviles en régimen de pasaje (Unidades)': 'Febrero_2023 Automóviles En Régimen De Pasaje', 'Unnamed: 112': 'Febrero_2024 Automóviles En Régimen De Pasaje',
             'Febrero Automóviles en régimen de mercancía (Unidades)': 'Febrero_2023 Automóviles En Régimen De Mercancía', 'Unnamed: 117': 'Febrero_2024 Automóviles En Régimen De Mercancía'}

In [16]:
df_febrero.columns

Index(['Autoridad Portuaria', 'Febrero Graneles Líquidos', 'Unnamed: 2',
       'Febrero Graneles Sólidos', 'Unnamed: 7', 'Febrero Mercancía General',
       'Unnamed: 12', 'Febrero Mercancía general en contenedores',
       'Unnamed: 17', 'Febrero Pesca', 'Unnamed: 22',
       'Febrero Avituallamiento', 'Unnamed: 27',
       'Febrero Avituallamiento de combustibles líquidos', 'Unnamed: 32',
       'Febrero Tráfico interior', 'Unnamed: 37',
       'Febrero Mercancías en tránsito', 'Unnamed: 42',
       'Febrero Mercancías en tránsito en contenedores', 'Unnamed: 47',
       'Febrero Tráfico Ro-Ro', 'Unnamed: 52',
       'Febrero Unidades de transporte intermodal Ro-Ro UTIS', 'Unnamed: 57',
       'Febrero Contenedores TEUS', 'Unnamed: 62',
       'Febrero Contenedores en tránsito TEUS', 'Unnamed: 67',
       'Febrero Contenedores entrada-salida nacional TEUS', 'Unnamed: 72',
       'Febrero Contenedores entrada-salida exterior TEUS', 'Unnamed: 77',
       'Febrero Buques mercantes (Número)', 'Unnamed: 82',
       'Febrero Buques mercantes (G.T.)', 'Unnamed: 87',
       'Febrero Buques de crucero (Número)', 'Unnamed: 92',
       'Febrero Pasajeros en régimen de transporte y de crucero (Número)',
       'Unnamed: 97', 'Febrero Pasajeros en régimen de transporte (Número)',
       'Unnamed: 102', 'Febrero Pasajeros de crucero (Número)', 'Unnamed: 107',
       'Febrero Automóviles en régimen de pasaje (Unidades)', 'Unnamed: 112',
       'Febrero Automóviles en régimen de mercancía (Unidades)',
       'Unnamed: 117'],
      dtype='object')

In [17]:
pd.options.display.max_columns = None

In [18]:
df_febrero = df_febrero.rename(columns=Renombrar_febrero)

In [19]:
df_febrero.head(4)

,Autoridad Portuaria,Febrero_2023 t Graneles Líquidos,Febrero_2024 t Graneles Líquidos,Febrero_2023 t Graneles Sólidos,Febrero_2024 t Graneles Sólidos,Febrero Mercancía General,Febrero_2024 t Mercancía General,Febrero_2023 t Mercancía General Contenedores,Febrero_2024 t Mercancía General Contenedores,Febrero_2023 t Pesca,Febrero_2024 t Pesca,Febrero_2023 t Avituallamiento,Febrero_2024 t Avituallamiento,Febrero_2023 t Avituallamiento De Combustibles Líquidos,Febrero_2024 t Avituallamiento De Combustibles Líquidos,Febrero_2023 t Tráfico Interior,Febrero_2024 t Tráfico Interior,Febrero_2023 t Mercancías En Tránsito,Febrero_2024 t Mercancías En Tránsito,Febrero_2023 t Mercancías En Tránsito En Contenedores,Febrero_2024 t Mercancías En Tránsito En Contenedores,Febrero_2023 t Tráfico Ro-Ro,Febrero_2024 t Tráfico Ro-Ro,Febrero Unidades de transporte intermodal Ro-Ro UTIS,Febrero_2024 UTIS Ro-Ro,Febrero_2023 TEUS Contenedores,Febrero_2024 TEUS Contenedores,Febrero_2023 TEUS Contenedores En Tránsito,Febrero_2024 TEUS Contenedores En Tránsito,Febrero_2023 TEUS Contenedores Entrada-Salida Nacional,Febrero_2024 TEUS Contenedores Entrada-Salida Nacional,Febrero_2023 TEUS Contenedores Entrada-Salida Exterior,Febrero_2024 TEUS Contenedores Entrada-Salida Exterior,Febrero_2023 Unidades Buques Mercantes,Febrero_2024 Unidades Buques Mercantes,Febrero_2023 G.T. Buques Mercantes,Febrero_2024 G.T. Buques Mercantes,Febrero_2023 Unidades Buques De Crucero,Febrero_2024 Unidades Buques De Crucero,Febrero_2023 Pasajeros En Régimen De Transporte Y De Crucero,Febrero_2024 Pasajeros En Régimen De Transporte Y De Crucero,Febrero_2023 Pasajeros En Régimen De Transporte,Febrero_2024 Pasajeros En Régimen De Transporte,Febrero_2023 Pasajeros De Crucero,Febrero_2024 Pasajeros De Crucero,Febrero_2023 Automóviles En Régimen De Pasaje,Febrero_2024 Automóviles En Régimen De Pasaje,Febrero_2023 Automóviles En Régimen De Mercancía,Febrero_2024 Automóviles En Régimen De Mercancía
1,A Coruña,895370,747204,542383,288615,57323,14295,0,0,1385.374,1002.014,3713,2130,2599,1310,0,0,315786,7917,0,0,0,0,0,0,0.00,0.00,0.0,0.0,0.0,0.0,0.00,0.00,96,70,1545849,1185147,0,2,0,3714,0,0,0,3714,0,0,0,0
2,Alicante,0,1848,135408,175579,96732,92710,89634,89152,0,0,1447,2312,186,102,0,0,0,580,0,580,51,907,0,0,13856.75,14240.75,0.0,56.0,11734.5,12023.5,2122.25,2161.25,53,55,816249,664578,4,0,18333,11828,8555,11828,9778,0,1938,4102,142,241
3,Almería,3689,19338,313763,256103,97314,116222,9285,18881,145.575,174.661,5090,4973,2304,2186,0,0,13,0,13,0,56033,65593,2957,3579,1335.00,1055.00,2.0,0.0,996.0,233.0,337.00,822.00,111,125,1876793,1887440,0,0,22979,27115,22979,27115,0,0,6871,8314,152,230
4,Avilés,72394,29158,223174,168150,83122,70654,0,0,634.812,505.321,3272,2441,1043,737,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.0,0.0,0.0,0.0,0.00,0.00,58,54,448131,463485,0,0,0,0,0,0,0,0,0,0,0,0

## Marzo

In [20]:
ruta_marzo = os.path.join('C:/Users/Encarni/Desktop/TFM/Tablas_descargadas/Modificados_pestaña/2024/3_marzo_2024.xlsx')
df_marzo = pd.read_excel(ruta_marzo)
display(df_marzo)

,Autoridad Portuaria,Marzo Graneles Líquidos,Unnamed: 2,Acumulado desde Marzo Graneles Líquidos,Unnamed: 4,Unnamed: 5,Marzo Graneles Sólidos,Unnamed: 7,Acumulado desde Marzo Graneles Sólidos,Unnamed: 9,Unnamed: 10,Marzo Mercancía General,Unnamed: 12,Acumulado desde Marzo Mercancía General,Unnamed: 14,Unnamed: 15,Marzo Mercancía general en contenedores,Unnamed: 17,Acumulado desde Marzo Mercancía General en contenedores,Unnamed: 19,Unnamed: 20,Marzo Pesca,Unnamed: 22,Acumulado desde Marzo Pesca,Unnamed: 24,Unnamed: 25,Marzo Avituallamiento,Unnamed: 27,Acumulado desde Marzo Avituallamiento,Unnamed: 29,Unnamed: 30,Marzo Avituallamiento de combustibles líquidos,Unnamed: 32,Acumulado desde Marzo Avituallamiento de combustibles líquidos,Unnamed: 34,Unnamed: 35,Marzo Tráfico interior,Unnamed: 37,Acumulado desde Marzo Tráfico interior,Unnamed: 39,Unnamed: 40,Marzo Mercancías en tránsito,Unnamed: 42,Acumulado desde Marzo Mercancías en tránsito,Unnamed: 44,Unnamed: 45,Marzo Mercancías en tránsito en contenedores,Unnamed: 47,Acumulado desde Marzo Mercancías en tránsito en contenedores,Unnamed: 49,Unnamed: 50,Marzo Tráfico Ro-Ro,Unnamed: 52,Acumulado desde Marzo Tráfico Ro-Ro,Unnamed: 54,Unnamed: 55,Marzo Unidades de transporte intermodal Ro-Ro UTIS,Unnamed: 57,Acumulado desde Marzo Unidades de transporte intermodal Ro-Ro UTIS,Unnamed: 59,Unnamed: 60,Marzo Contenedores TEUS,Unnamed: 62,Acumulado desde Marzo Contenedores TEUS,Unnamed: 64,Unnamed: 65,Marzo Contenedores en tránsito TEUS,Unnamed: 67,Acumulado desde Marzo Contenedores en tránsito TEUS,Unnamed: 69,Unnamed: 70,Marzo Contenedores entrada-salida nacional TEUS,Unnamed: 72,Acumulado desde Marzo Contenedores entrada-salida nacional TEUS,Unnamed: 74,Unnamed: 75,Marzo Contenedores entrada-salida exterior TEUS,Unnamed: 77,Acumulado desde Marzo Contenedores entrada-salida exterior TEUS,Unnamed: 79,Unnamed: 80,Marzo Buques mercantes (Número),Unnamed: 82,Acumulado desde Marzo Buques mercantes (Número),Unnamed: 84,Unnamed: 85,Marzo Buques mercantes (G.T.),Unnamed: 87,Acumulado desde Marzo Buques mercantes (G.T.),Unnamed: 89,Unnamed: 90,Marzo Buques de crucero (Número),Unnamed: 92,Acumulado desde Marzo Buques de crucero (Número),Unnamed: 94,Unnamed: 95,Marzo Pasajeros en régimen de transporte y de crucero (Número),Unnamed: 97,Acumulado desde Marzo Pasajeros en régimen de transporte y de crucero (Número),Unnamed: 99,Unnamed: 100,Marzo Pasajeros en régimen de transporte (Número),Unnamed: 102,Acumulado desde Marzo Pasajeros en régimen de transporte (Número),Unnamed: 104,Unnamed: 105,Marzo Pasajeros de crucero (Número),Unnamed: 107,Acumulado desde Marzo Pasajeros de crucero (Número),Unnamed: 109,Unnamed: 110,Marzo Automóviles en régimen de pasaje (Unidades),Unnamed: 112,Acumulado desde Marzo Automóviles en régimen de pasaje (Unidades),Unnamed: 114,Unnamed: 115,Marzo Automóviles en régimen de mercancía (Unidades),Unnamed: 117,Acumulado desde Marzo Automóviles en régimen de mercancía (Unidades),Unnamed: 119,Unnamed: 120
0,NaN,2023 t,2024 t,2023 t,2024 t,Var. (%),2023 t,2024 t,2023 t,2024 t,Var. (%),2023 t,2024 t,2023 t,2024 t,Var. (%),2023 t,2024 t,2023 t,2024 t,Var. (%),2023 t,2024 t,2023 t,2024 t,Var. (%),2023 t,2024 t,2023 t,2024 t,Var. (%),2023 t,2024 t,2023 t,2024 t,Var. (%),2023 t,2024 t,2023 t,2024 t,Var. (%),2023 t,2024 t,2023 t,2024 t,Var. (%),2023 t,2024 t,2023 t,2024 t,Var. (%),2023 t,2024 t,2023 t,2024 t,Var. (%),2023,2024,2023,2024,Var. (%),2023.00,2024.00,2023.00,2024.00,Var. (%),2023.00,2024.00,2023.00,2024.00,Var. (%),2023.00,2024.00,2023.00,2024.00,Var. (%),2023.00,2024.00,2023.00,2024.00,Var. (%),2023,2024,2023,2024,Var. (%),2023 GT,2024 GT,2023 GT,2024 GT,Var. (%),2023,2024,2023,2024,Var. (%),2023,2024,2023,2024,Var. (%),2023,2024,2023,2024,Var. (%),2023,2024,2023,2024,Var. (%),2023,2024,2023,2024,Var. (%),2023,2024,2023,2024,Var. (%)
1,A Coruña,591403,863302,2163428,2330412,7.718491,544458,279003,1608288,973751,-39.45419,80350,50451,178670,94535,-47.089607,0,0,66,0,-100,2442.947,1445.893,5031.319,3596.819,-28.51141,7792,7032,13532,12065,-10.84097,3394,2081,7481,5636,-24.662478,0,0,0,0,,318609,7920,902789,56861,-93.701629,0,0,0,0,,0,0,0,0,,0,0,0,0,,0.00,0.00,6.00,0.00,-100,0.00,0.00,0.00,0.00,,0.00,0.00,0.00,0.00,,0.00,0.00,6.00,0.00,-100,86,98,263,249,-5.323194,1659967,1843269,4664657,4584655,-1.715067,4,5,8,11,37.5,10565,13679,17149,27097,58.009213,0,0,0,0,,10565,13679,17149,27097,58.009213,0,0,0,0,,0,0,0,0,
2,Alicante,6504,9103,11957,19958,66.914778,276103,220934,603270,505636,-16.18413,107639,110251,300576,289110,-3.814676,96319,105093,275299,271526,-1.37051,0,0,0,0,,1509,1554,4820,4747,-1.514523,204,79,573,236,-58.813264,0,0,0,0,,0,1901,1100,2778,152.545455,0,1901,1100,2778,152.545455,4804,406,9685,7523,-22.32318,214,5,400,237,-40.75,14534.00,16216.50,42644.50,41112.00,-3.593664,0.00,203.00,109.50,297.00,171.232877,13380.25,13920.50,36905.25,34647.50,-6.117693,1153.75,2093.00,5629.75,6167.50,9.551934,57,67,168,176,4.761905,745037,857634,2538978,2070392,-18.455694,3,2,11,3,-72.727273,13212,9669,51720,29648,-42.675947,7243,7215,25160,25033,-0.504769,5969,2454,26560,4615,-82.624247,1687,3133,6142,8815,43.520026,95,243,315,535,69.84127
3,Almería,0,7131,8227,44980,446.736356,368991,193740,981838,705969,-28.097201,103864,96700,275895,322269,16.808568,15162,17915,36119,52403,45.084305,110.205,78.781,441.952,481.947,9.049625,5894,4929,16191,15990,-1.24143,3797,2295,9084,7103,-21.807574,0,0,0,0,,0,0,15,0,-100,0,0,15,0,-100,73554,66748,179107,195685,9.25592,3859,3572,9309,10253,10.140724,1058.50,1005.00,3687.00,3176.75,-13.839165,0.00,0.00,3.00,0.00,-100,416.00,227.00,2158.00,917.75,-57.472196,642.50,778.00,1526.00,2259.00,48.034076,128,126,351,385,9.68661,2148677,2142646,5923184,6161973,4.03143,0,0,0,0,,26930,26812,85343,94752,11.024923,26930,26812,85343,94752,11.024923,0,0,0,0,,8321,8806,24899,28565,14.723483,176,218,498,687,37.951807
4,Avilés,56189,55801,184000,146380,-20.445652,244437,140166,739369,542390,-26.641501,128771,139425,298188,294339,-1.290796,0,0,0,0,,1056.976,1300.444,2173.248,2251.911,3.619605,5070,3727,12781,9118,-28.659729,1377,1609,4261,3396,-20.300399,0,0,0,0,,0,0,0,0,,0,0,0,0,,0,0,0,0,,0,0,0,0,,0.00,0.00,0.00,0.00,,0.00,0.00,0.00,0.00,,0.00,0.00,0.00,0.00,,0.00,0.00,0.00,0.00,,70,66,192,176,-8.333333,554362,521111,1491988,1386669,-7.058971,0,0,0,0,,0,0,0,0,,0,0,0,0,,0,0,0,0,,0,0,0,0,,0,0,0,0,
5,Bahía de Algeciras,2321077,2356131,6599261,7594670,15.083643,123376,260,190240,66596,-64.993692,6273346,5890166,17314372,17217086,-0.56188,4854049,4828568,13454485,14011883,4.142842,38.752,40.26,150.382,200.226,33.144924,349632,269694,828636,911033,9.943691,335382,258620,786914,869235,10.461245,352409,262428,807820,890971,10.293258,5318723,5229906,15188727,15922868,4.83346,4334056,4324863,11954491,12536821,4.871224,1413888,1071582,3839538,3216982,-16.214347,46720,45797,127128,136019,6.993739,400314.00,396089.00,1119100.00,1171425.00,4.675632,336648.00,345468.00,933290.00,994295.00,6.536553,4.00,14.00,8.00,14.00,75,63662.00,50607.00,185802.00,177116.00,-4.674869,2359,2177,6495,6927,6.65127,45144327,41527204,121586039,134573950,10.682074,0,0,0,0,,312991,316724,865689,969787,12.024873,312991,316724,865689,969787,12.024873,0,0,0,0,,61755,66886,177848,210124,18.148082,350,340,828,1003,21.135266
6,Bahía de Cádiz,140155,77604,451768,118665,-73.733199,148365,110024,448391,460737,2.7534,189757,200326,511964,550131,7.455016,130404,139493,354890,383394,8.031784,1050.968,844.239,2593.906,2288.649,-11.768237,10305,7514,26128,24402,-6.60594,2609,1272,6195,8767,41.517353,0,0,0,0,,150417,95191,487240,160556,-67.047861,18815,17587,53032,49226,-7.176799,76923,71437,209711,205129,-2.184912,2328,2263,6277,6612,5.336944,17027.00,19319.75,47270.00,51892.75,9.779458,1638.25,1849.75,4693.75,4705.00,0.23968,13047.50,14599.00,36736.50,39677.25,8.004981,2341.25,2871.00,5839.75,7510.50,28.609958,123,94,360,322,-10.555556,2591176,1808262,7455404,6011778,-19.363485,16,14,43,31,-27.906977,24850,21071,79308,66960,-15.569678,1292,1478,4469,4805,7.518461,23558,19593,74839,62155,-16.948383,771,929,2695,2948,9.387755,1789,1285,5480,4268,-22.116788
7,Baleares,68656,126825,221911,309289,39.375245,23303,16916,107794,80698,-25.136835,1271413,1195038,3149366,3283005,4.243362,30084,28429,75779,74642,-1.500416,112.903,142.471,276.032,306.041,10.871566,5410,5877,11471,18507,61.337285,127,217,386,433,12.176166,488,251,1187,539,-54.591407,1122,884,2674,2545,-4.824233,0,0,0,0,,1264556,1183433,3128330,3250058,3.89115,60671,54892,148233,151135,1.957729,8332.00,6801.00,21026.00,19557.00,-6.986588,0.00,0.00,0.00,0.00,,8332.00,6801.00,21024.00,19557.00,-6.97774,0.00,0.00,2.00,0.00,-100,2836,3056,7804,8806,12.839569,17401718,18816258,49856784,51970414,4.239403,17,19,44,45,2.272727,383131,432348,936168,1025263,9.516988,327390,368670,777561,860162,10.623089,55741,63678,158607,165101,4.094397,64703,85251,161826,194120,19.956002,13670,12338,25765,31211,21.137202
8,Barcelona,1166042,1189649,3226793,2968304,-8.010709,499576,396163,1282222,1082934,-15.542394,3794903,4563660,10719973,12453171,16.167933,2745140,3550731,8056825,9710700,20.527627,169.035,211.547,319.5,457.062,43.055399,116022,102324,340681,308933,-9.318982,97442,82699,293383,265397,-9.539067,0,0,0,0,,1626892,2561161,4827288,6728102,39.376437,1219856,1907463,3690573,5352781,45.039293,1089051,1017725,2741934,2800347,2.130358,38690,36306,96392,99620,3.348826,259357.25,348007.00,773858.25,951655.25,22.975396,94237.50,158349.50,301913.00,451035.50,49.39254,80501.75,85211.00,212587.75,228922.25,7.683651,84618.00,104438.50,259357.50,271689.50,4.754827,701,698,1946,1941,-0.256937,26863389,26767254,74024262,74891693,1.17182,32,27,78,65,-16.666667,216019,254704,515207,567442,10.138643,96134,121203,223115,247966,11.138202,119885,133501,292092,319476,9.375128,23272,29316,62293,69910,12.227698,77057,74032,196955,184625,-6.260313
9,Bilbao,1801755,2114003,4810427,5716075,18.826769,378813,292386,991504,837098,-15.572907,694522,777691,1921705,1905348,-0.851171,426316,456400,1279053,1234550,-3.479371,0,0,0,0,,10954,12351,29918,30880,3.215456,5696,6546,15745,16272,3.347094,0,0,0,0,,2212,2239,7542,12465,65.274463,1791,2239,7121,12465,75.04564,81483,88992,231502,194643,-15.921677,3156,2068,9142,4552,-50.207832,39909.00,42956.50,123838.25,113748.50,-8.147523,166.25,154.75,513.75,967.50,88.321168,3993.00,1782.00,12016.75,4792.75,-60.116088,35749.75,41019.75,111307.75,107988.25,-2.982272,228,227,621,593,-4.508857,4271152,4423032,11458183,11714348,2.235651,0,0,0,0,,3883,0,8867,49,-99.447389,3883,0,8867,49,-99.447389,0,0,0,0,,1662,0,3554,0,-100,7606,1719,12222,5423,-55.629193
10,Cartagena,2605078,2030458,7057226,6806908,-3.546974,689649,652451,2117764,2271696,7.26861,104283,81372,239219,198563,-16.995306,50466,59838,135837,135439,-0.292998,21.022,10.537,37.128,67.715,82.382568,20756,13115,42205,37751,-10.553252,1067,739,2729,2859,4.76365,0,0,0,0,,77539,2460,380640,82946,-78.208806,29,0,29,0,-100,3507,2460,7308,2460,-66.338259,0,0,0,0,,3386.25,5298.00,9520.75,10903.00,14.518289,2.00,0.00,2.00,0.00,-100,561.00,1335.00,1825.00,2704.00,48.164384,2823.25,3963.00,7693.75,8199.00,6.567019,177,158,475,474,-0.210526,3930557,3403804,10974414,9844158,-10.29901,4,4,12,4,-66.666667,4401,5094,16891,5094,-69.841928,0,0,0,0,,4401,5094,16891,5094,-69.841928,0,0,0,0,,0,2002,11,2006,18136.363636
11,Castellón,751441,818476,2157076,2195676,1.789459,656447,613625,1700882,1443750,-15.117568,113933,94405,288391,245177,-14.984518,100561,93199,263863,238456,-9.62886,212.056,224.823,566.238,817.101,44.303455,2122,2107,6755,6528,-3.360474,0,0,0,0,,0,0,0,0,,255,6871,2544,9811,285.652516,255,2871,2544,5811,128.419811,11239,5534,36579,17304,-52.694169,8,0,17,0,-100,6220.00,6859.00,17728.00,17111.25,-3.47896,92.00,146.00,415.00,296.00,-28.674699,468.00,688.00,1132.00,1666.75,47.239399,5660.00,6025.00,16181.00,15148.50,-6.380941,117,107,331,310,-6.344411,1634468,1646304,4582814,4428326,-3.371029,0,0,0,0,,0,0,0,0,,0,0,0,0,,0,0,0,0,,0,0,0,0,,62,22,241,77,-68.049793
12,Ceuta,53938,46962,155663,138895,-10.771988,0,1400,2400,1400,-41.666667,50002,42234,130062,137045,5.368978,6430,5397,16865,17690,4.891788,0,0,0.508,0,-100,62899,31327,164490,108203,-34.219101,61181,29399,160157,102751,-35.843578,0,0,0,0,,0,0,0,0,,0,0,0,0,,49352,41974,128762,135189,4.991379,2939,2525,7675,8105,5.602606,540.00,433.00,1430.50,1384.00,-3.250612,0.00,0.00,0.00,0.00,,530.00,422.00,1384.50,1327.00,-4.153124,10.00,11.00,46.00,57.00,23.913043,843,812,2352,2399,1.998299,6480239,5225229,17694417,15517054,-12.305367,4,0,8,0,-100,146382,141964,385519,389180,0.949629,139069,141964,371696,389180,4.703844,7313,0,13823,0,-100,31187,33695,86551,95330,10.143153,128,306,351,595,69.51567
13,Ferrol-San Cibrao,309451,192813,1244734,485042,-61.032478,330196,466005,876139,1125590,28.471624,98565,68611,332480,162460,-51.13691,43659,10610,137977,29237,-78.810236,23.913,9.962,46.327,25.514,-44.926285,1356,1136,3150,2348,-25.460317,792,562,1816,1168,-35.682819,0,0,0,0,,121342,66376,164457,327693,99.257557,0,199,0,488,,745,1080,4083,2821,-30.908646,9,1,21,5,-76.190476,3360.50,1085.00,11946.00,2845.50,-76.180311,0.00,49.50,0.00,88.25,,877.75,138.25,3361.50,433.25,-87.111409,2482.75,897.25,8584.50,2324.00,-72.927952,83,83,254,196,-22.834646,1420347,1201670,4391879,2800316,-36.238772,0,0,1,1,0,0,0,749,964,28.70494,0,0,0,0,,0,0,749,964,28.70494,0,0,0,0,,38,0,60,0,-100
14,Gijón,95963,99494,283392,348892,23.112861,1536601,878531,4317193,2773733,-35.751471,123707,243371,345844,494475,42.976313,54160,117658,169509,261520,54.280894,1765.627,909.833,1947.31,1230.821,-36.793782,0,0,7423,0,-100,0,0,7423,0,-100,0,0,0,0,,545969,164484,1800851,549505,-69.486371,278,0,283,8,-97.173145,0,0,0,0,,0,0,0,0,,3909.00,8252.00,12392.00,18468.00,49.031633,69.00,0.00,71.00,4.00,-94.366197,577.00,676.00,2359.00,1358.00,-42.433234,3263.00,7576.00,9962.00,17106.00,71.712508,120,91,303,256,-15.511551,2079182,1393349,5221796,4097691,-21.527172,1,0,1,0,-100,985,0,985,0,-100,0,0,0,0,,985,0,985,0,-100,0,0,0,0,,0,2,1,5,400
15,Huelva,1253542,1965129,5596175,6094611,8.906726,355073,399016,1325977,1240355,-6.457276,111494,187957,301175,447091,48.448908,50618,80948,133314,205034,53.797801,21.828,7.143,46.452,27.191,-41.464307,13773,9504,32650,17150,-47.473201,12091,7332,26650,11074,-58.446529,0,10188,13019,29796,128.865504,120480,322956,431297,696300,61.443275,0,19096,6,46204,769966.666667,58117,63810,159419,178586,12.023034,2894,3290,7938,8942,12.648022,6727.50,10381.50,18463.00,27583.00,49.396089,0.00,1331.25,1.00,3428.25,342725,5875.25,7995.50,16118.00,21290.25,32.089899,852.25,1054.75,2344.00,2864.50,22.205631,155,203,475,572,20.421053,2594511,3405172,9629396,10387780,7.875717,0,0,0,0,,4616,5089,12883,13353,3.648219,4616,5089,12883,13353,3.648219,0,0,0,0,,2790,3124,7846,7900,0.688249,814,1522,2401,3977,65.639317
16,Las Palmas,823575,687073,2027316,2037589,0.506729,55844,29148,109629,78436,-28.453238,1626453,1663690,4232505,4789382,13.157149,1198891,1281883,3069040,3615390,17.801984,27.025,34.587,120.164,61.522,-48.801638,214693,217700,643901,698407,8.464966,187986,189868,554823,617394,11.277651,0,6,0,6,,1240434,1124773,2978855,3318107,11.388671,808624,905998,2004443,2533722,26.405291,426039,404988,1163575,1216557,4.553381,30328,27380,82089,82671,0.708987,115966.00,116856.00,285851.00,328860.00,15.045951,63713.00,66292.00,142841.00,183726.00,28.622734,45271.00,43820.00,124537.00,125755.00,0.978023,6982.00,6744.00,18473.00,19379.00,4.904455,1082,1104,3156,3277,3.833967,25548644,26599974,75253279,80077749,6.410976,95,75,258,227,-12.015504,334594,366574,958785,1037567,8.216858,104946,128186,304232,332680,9.350759,229648,238388,654553,704887,7.689828,46503,54012,132675,142372,7.308837,57332,17941,103832,86363,-16.824293
17,Málaga,6000,19952,20910,29577,41.449067,108583,110579,340862,409312,20.081441,85489,197683,193315,355608,83.952616,23545,144984,64368,179768,179.281631,6.647,0.444,26.415,62.579,136.90706,6564,4673,16883,14599,-13.528401,2841,3105,6855,8334,21.575492,0,0,0,0,,3846,145632,9565,167368,1649.796132,2694,120580,5333,120795,2165.047815,62576,49307,133163,169269,27.114138,3373,1798,7578,7682,1.372394,3312.25,13747.00,8181.50,17334.00,111.868239,1334.25,11506.00,2662.50,11613.00,336.169014,890.00,515.00,2369.00,1642.00,-30.688054,1088.00,1726.00,3150.00,4079.00,29.492063,142,117,322,346,7.453416,3446390,3870003,8205046,9995585,21.822413,16,5,31,10,-67.741935,48987,31044,117192,84922,-27.536009,22382,23849,60917,66364,8.941675,26605,7195,56275,18558,-67.022657,4058,5391,11335,14390,26.951919,8027,15976,13908,41873,201.071326
18,Marín y Ría de Pontevedra,0,0,0,0,,53295,87278,221063,324373,46.733284,80222,89264,260486,261011,0.201546,37196,36334,120256,101420,-15.663252,271.569,141.956,653.548,501.85,-23.211455,1323,1822,3991,5849,46.554748,561,1019,1598,3375,111.201502,0,0,0,0,,0,727,408,732,79.411765,0,187,408,192,-52.941176,0,0,0,0,,0,0,0,0,,3278.75,3943.25,10919.00,10609.50,-2.834509,0.00,11.00,204.00,12.00,-94.117647,388.00,191.25,1103.00,551.00,-50.045331,2890.75,3741.00,9612.00,10046.50,4.520391,36,42,100,120,20,177050,268665,590105,792804,34.34965,0,0,0,0,,0,0,0,0,,0,0,0,0,,0,0,0,0,,0,0,0,0,,11,19,19,181,852.631579
19,Melilla,4509,4040,14054,16998,20.947773,0,0,1499,0,-100,42976,33915,110457,108074,-2.157401,4014,2766,11044,9337,-15.456356,0,0,0,0,,73,0,1852,106,-94.276458,0,0,0,0,,0,0,0,0,,0,0,0,0,,0,0,0,0,,42976,33915,110457,108074,-2.157401,2792,2223,7249,7117,-1.820941,577.00,426.00,1514.00,1381.50,-8.751651,0.00,0.00,0.00,0.00,,567.00,422.00,1501.00,1373.50,-8.494337,10.00,4.00,13.00,8.00,-38.461538,97,92,274,280,2.189781,2260116,2642447,6299693,7986934,26.782908,1,1,1,1,0,32700,35283,93796,106636,13.689283,31943,34695,93039,106048,13.982308,757,588,757,588,-22.324967,6673,8650,19833,25964,30.913125,163,164,522,11313,2067.241379
20,Motril,110008,94085,333880,338140,1.275908,29612,66015,79731,229577,187.939446,65165,49784,150368,153051,1.784289,878,214,1689,662,-60.80521,57.819,47.485,149.01,201.183,35.013086,1659,2066,5633,5417,-3.834546,788,1292,2660,3454,29.849624,0,0,0,0,,12716,1607,39862,3619,-90.921178,0,0,0,0,,60955,42285,130706,131170,0.354995,2297,1786,4752,5494,15.614478,156.00,34.00,300.00,97.50,-67.5,0.00,0.00,0.00,0.00,,0.00,0.00,0.00,0.00,,156.00,34.00,300.00,97.50,-67.5,68,71,194,223,14.948454,1091598,958077,2685963,2841957,5.807749,0,0,0,0,,3538,7726,11157,22217,99.130591,3538,7726,11157,22217,99.130591,0,0,0,0,,805,2678,2545,7033,176.345776,6,8,1020,18,-98.235294
21,Pasaia,0,0,0,0,,104616,59123,230875,191096,-17.22967,254603,232206,635160,635769,0.095881,0,0,0,0,,2821.874,1996.728,6786.875,4288.172,-36.816694,1965,2243,6145,6659,8.364524,777,814,2840,2666,-6.126761,0,0,0,0,,1029,2140,5313,9040,70.148692,0,0,0,0,,58310,59251,158002,160465,1.558841,347,314,864,895,3.587963,0.00,0.00,0.00,0.00,,0.00,0.00,0.00,0.00,,0.00,0.00,0.00,0.00,,0.00,0.00,0.00,0.00,,83,68,227,206,-9.251101,700434,626292,1824681,1733284,-5.00893,0,0,0,0,,1,0,2,0,-100,0,0,0,0,,1,0,2,0,-100,0,0,0,0,,24345,24885,65081,68033,4.535886
22,Santa Cruz de Tenerife,282523,367270,966914,1034813,7.022238,42165,41199,82543,83107,0.68328,740762,671575,2037667,2148634,5.445787,363182,313748,1047112,983083,-6.114819,321.647,204.083,590.237,482.072,-18.32569,77763,81393,222231,215876,-2.859637,59838,64654,161134,163892,1.711619,131,135,389,487,25.192802,61860,50444,249364,189004,-24.205579,59212,34964,240931,153192,-36.41665,397181,369647,1035307,1174966,13.489622,28910,24562,75343,75638,0.391543,46194.00,37529.00,135384.00,117377.00,-13.300685,6663.00,1796.00,29759.00,8289.00,-72.146241,34111.00,32313.00,93999.00,95854.00,1.973425,5420.00,3420.00,11626.00,13234.00,13.831068,1428,1458,4156,4211,1.323388,20066981,20706585,58013721,58504967,0.846776,86,67,212,188,-11.320755,604651,651180,1749630,1845307,5.468413,434902,496030,1269665,1371042,7.984547,169749,155150,479965,474265,-1.187587,130628,153857,375774,411753,9.574638,7124,6447,19288,19877,3.053712

In [21]:
df_marzo.columns

Index(['Autoridad Portuaria', 'Marzo Graneles Líquidos', 'Unnamed: 2',
       'Acumulado desde Marzo Graneles Líquidos', 'Unnamed: 4', 'Unnamed: 5',
       'Marzo Graneles Sólidos', 'Unnamed: 7',
       'Acumulado desde Marzo Graneles Sólidos', 'Unnamed: 9',
       ...
       'Marzo Automóviles en régimen de pasaje (Unidades)', 'Unnamed: 112',
       'Acumulado desde Marzo Automóviles en régimen de pasaje (Unidades)',
       'Unnamed: 114', 'Unnamed: 115',
       'Marzo Automóviles en régimen de mercancía (Unidades)', 'Unnamed: 117',
       'Acumulado desde Marzo Automóviles en régimen de mercancía (Unidades)',
       'Unnamed: 119', 'Unnamed: 120'],
      dtype='object', length=121)

In [22]:
df_marzo = df_marzo.drop(['Acumulado desde Marzo Graneles Líquidos', 'Unnamed: 4', 'Unnamed: 5' ], axis=1)
df_marzo = df_marzo.drop(['Acumulado desde Marzo Graneles Sólidos', 'Unnamed: 9', 'Unnamed: 10'], axis=1)
df_marzo = df_marzo.drop(['Acumulado desde Marzo Mercancía General', 'Unnamed: 14', 'Unnamed: 15'], axis=1)
df_marzo = df_marzo.drop(['Acumulado desde Marzo Mercancía General en contenedores', 'Unnamed: 19', 'Unnamed: 20'], axis=1)
df_marzo = df_marzo.drop(['Acumulado desde Marzo Pesca', 'Unnamed: 24', 'Unnamed: 25'], axis=1)
df_marzo = df_marzo.drop(['Acumulado desde Marzo Avituallamiento', 'Unnamed: 29', 'Unnamed: 30'], axis=1)
df_marzo = df_marzo.drop(['Acumulado desde Marzo Avituallamiento de combustibles líquidos', 'Unnamed: 34', 'Unnamed: 35'], axis=1)
df_marzo = df_marzo.drop(['Acumulado desde Marzo Tráfico interior', 'Unnamed: 39', 'Unnamed: 40'], axis=1)
df_marzo = df_marzo.drop(['Acumulado desde Marzo Mercancías en tránsito', 'Unnamed: 44', 'Unnamed: 45'], axis=1)
df_marzo = df_marzo.drop(['Acumulado desde Marzo Mercancías en tránsito en contenedores', 'Unnamed: 49', 'Unnamed: 50'], axis=1)
df_marzo = df_marzo.drop(['Acumulado desde Marzo Tráfico Ro-Ro', 'Unnamed: 54', 'Unnamed: 55'], axis=1)
df_marzo = df_marzo.drop(['Acumulado desde Marzo Unidades de transporte intermodal Ro-Ro UTIS', 'Unnamed: 59', 'Unnamed: 60'], axis=1)
df_marzo = df_marzo.drop(['Acumulado desde Marzo Contenedores TEUS', 'Unnamed: 64', 'Unnamed: 65'], axis=1)
df_marzo = df_marzo.drop(['Acumulado desde Marzo Contenedores en tránsito TEUS', 'Unnamed: 69', 'Unnamed: 70'], axis=1)
df_marzo = df_marzo.drop(['Acumulado desde Marzo Contenedores entrada-salida nacional TEUS', 'Unnamed: 74', 'Unnamed: 75'], axis=1)
df_marzo = df_marzo.drop(['Acumulado desde Marzo Contenedores entrada-salida exterior TEUS', 'Unnamed: 79', 'Unnamed: 80'], axis=1)
df_marzo = df_marzo.drop(['Acumulado desde Marzo Buques mercantes (Número)', 'Unnamed: 84', 'Unnamed: 85'], axis=1)
df_marzo = df_marzo.drop(['Acumulado desde Marzo Buques mercantes (G.T.)', 'Unnamed: 89', 'Unnamed: 90'], axis=1)
df_marzo = df_marzo.drop(['Acumulado desde Marzo Buques de crucero (Número)', 'Unnamed: 94', 'Unnamed: 95'], axis=1)
df_marzo = df_marzo.drop(['Acumulado desde Marzo Pasajeros en régimen de transporte y de crucero (Número)', 'Unnamed: 99', 'Unnamed: 100'], axis=1)
df_marzo = df_marzo.drop(['Acumulado desde Marzo Pasajeros en régimen de transporte (Número)', 'Unnamed: 104', 'Unnamed: 105'], axis=1)
df_marzo = df_marzo.drop(['Acumulado desde Marzo Pasajeros de crucero (Número)', 'Unnamed: 109', 'Unnamed: 110'], axis=1)
df_marzo = df_marzo.drop(['Acumulado desde Marzo Automóviles en régimen de pasaje (Unidades)', 'Unnamed: 114', 'Unnamed: 115'], axis=1)
df_marzo = df_marzo.drop(['Acumulado desde Marzo Automóviles en régimen de mercancía (Unidades)', 'Unnamed: 119', 'Unnamed: 120'], axis=1)

In [23]:
Renombrar_marzo = {'Marzo Graneles Líquidos': 'Marzo_2023 t Graneles Líquidos', 'Unnamed: 2': 'Marzo_2024 t Graneles Líquidos',
             'Marzo Graneles Sólidos ': 'Marzo_2023 t Graneles Sólidos', 'Unnamed: 7': 'Marzo_2024 t Graneles Sólidos',
             'Marzo Mercancía General': 'Marzo_2023 t Mercancía General', 'Unnamed: 12': 'Marzo_2024 t Mercancía General',
             'Marzo Mercancía general en contenedores': 'Marzo_2023 t Mercancía General Contenedores', 'Unnamed: 17': 'Marzo_2024 t Mercancía General Contenedores',
             'Marzo Pesca': 'Marzo_2023 t Pesca', 'Unnamed: 22': 'Marzo_2024 t Pesca',
             'Marzo Avituallamiento': 'Marzo_2023 t Avituallamiento', 'Unnamed: 27': 'Marzo_2024 t Avituallamiento',
             'Marzo Avituallamiento de combustibles líquidos': 'Marzo_2023 t Avituallamiento De Combustibles Líquidos', 'Unnamed: 32': 'Marzo_2024 t Avituallamiento De Combustibles Líquidos',
             'Marzo Tráfico interior': 'Marzo_2023 t Tráfico Interior', 'Unnamed: 37': 'Marzo_2024 t Tráfico Interior',
             'Marzo Mercancías en tránsito': 'Marzo_2023 t Mercancías En Tránsito', 'Unnamed: 42': 'Marzo_2024 t Mercancías En Tránsito',
             'Marzo Mercancías en tránsito en contenedores': 'Marzo_2023 t Mercancías En Tránsito En Contenedores', 'Unnamed: 47': 'Marzo_2024 t Mercancías En Tránsito En Contenedores',
             'Marzo Tráfico Ro-Ro': 'Marzo_2023 t Tráfico Ro-Ro', 'Unnamed: 52': 'Marzo_2024 t Tráfico Ro-Ro',
             'Marzo Unidades de transporte intermodal Ro-Ro UTIS': 'Marzo_2023 UTIS Ro-Ro', 'Unnamed: 57': 'Marzo_2024 UTIS Ro-Ro', 
             'Marzo Contenedores TEUS': 'Marzo_2023 TEUS Contenedores', 'Unnamed: 62': 'Marzo_2024 TEUS Contenedores', 
             'Marzo Contenedores en tránsito TEUS': 'Marzo_2023 TEUS Contenedores En Tránsito', 'Unnamed: 67': 'Marzo_2024 TEUS Contenedores En Tránsito',
             'Marzo Contenedores entrada-salida nacional TEUS': 'Marzo_2023 TEUS Contenedores Entrada-Salida Nacional', 'Unnamed: 72': 'Marzo_2024 TEUS Contenedores Entrada-Salida Nacional',
             'Marzo Contenedores entrada-salida exterior TEUS': 'Marzo_2023 TEUS Contenedores Entrada-Salida Exterior', 'Unnamed: 77': 'Marzo_2024 TEUS Contenedores Entrada-Salida Exterior',
             'Marzo Buques mercantes (Número)': 'Marzo_2023 Unidades Buques Mercantes', 'Unnamed: 82': 'Marzo_2024 Unidades Buques Mercantes', 
             'Marzo Buques mercantes (G.T.)': 'Marzo_2023 G.T. Buques Mercantes', 'Unnamed: 87': 'Marzo_2024 G.T. Buques Mercantes',
             'Marzo Buques de crucero (Número)': 'Marzo_2023 Unidades Buques De Crucero', 'Unnamed: 92': 'Marzo_2024 Unidades Buques De Crucero',
             'Marzo Pasajeros en régimen de transporte y de crucero (Número)': 'Marzo_2023 Pasajeros En Régimen De Transporte Y De Crucero', 'Unnamed: 97': 'Marzo_2024 Pasajeros En Régimen De Transporte Y De Crucero',
             'Marzo Pasajeros en régimen de transporte (Número)': 'Marzo_2023 Pasajeros En Régimen De Transporte', 'Unnamed: 102': 'Marzo_2024 Pasajeros En Régimen De Transporte',
             'Marzo Pasajeros de crucero (Número)': 'Marzo_2023 Pasajeros De Crucero', 'Unnamed: 107': 'Marzo_2024 Pasajeros De Crucero',
             'Marzo Automóviles en régimen de pasaje (Unidades)': 'Marzo_2023 Automóviles En Régimen De Pasaje', 'Unnamed: 112': 'Marzo_2024 Automóviles En Régimen De Pasaje',
             'Marzo Automóviles en régimen de mercancía (Unidades)': 'Marzo_2023 Automóviles En Régimen De Mercancía', 'Unnamed: 117': 'Marzo_2024 Automóviles En Régimen De Mercancía'}

In [24]:
df_marzo = df_marzo.rename(columns=Renombrar_marzo)

In [25]:
df_marzo = df_marzo.drop(0, axis=0)

In [26]:
df_marzo.head(2)

,Autoridad Portuaria,Marzo_2023 t Graneles Líquidos,Marzo_2024 t Graneles Líquidos,Marzo Graneles Sólidos,Marzo_2024 t Graneles Sólidos,Marzo_2023 t Mercancía General,Marzo_2024 t Mercancía General,Marzo_2023 t Mercancía General Contenedores,Marzo_2024 t Mercancía General Contenedores,Marzo_2023 t Pesca,Marzo_2024 t Pesca,Marzo_2023 t Avituallamiento,Marzo_2024 t Avituallamiento,Marzo_2023 t Avituallamiento De Combustibles Líquidos,Marzo_2024 t Avituallamiento De Combustibles Líquidos,Marzo_2023 t Tráfico Interior,Marzo_2024 t Tráfico Interior,Marzo_2023 t Mercancías En Tránsito,Marzo_2024 t Mercancías En Tránsito,Marzo_2023 t Mercancías En Tránsito En Contenedores,Marzo_2024 t Mercancías En Tránsito En Contenedores,Marzo_2023 t Tráfico Ro-Ro,Marzo_2024 t Tráfico Ro-Ro,Marzo_2023 UTIS Ro-Ro,Marzo_2024 UTIS Ro-Ro,Marzo_2023 TEUS Contenedores,Marzo_2024 TEUS Contenedores,Marzo_2023 TEUS Contenedores En Tránsito,Marzo_2024 TEUS Contenedores En Tránsito,Marzo_2023 TEUS Contenedores Entrada-Salida Nacional,Marzo_2024 TEUS Contenedores Entrada-Salida Nacional,Marzo_2023 TEUS Contenedores Entrada-Salida Exterior,Marzo_2024 TEUS Contenedores Entrada-Salida Exterior,Marzo_2023 Unidades Buques Mercantes,Marzo_2024 Unidades Buques Mercantes,Marzo_2023 G.T. Buques Mercantes,Marzo_2024 G.T. Buques Mercantes,Marzo_2023 Unidades Buques De Crucero,Marzo_2024 Unidades Buques De Crucero,Marzo_2023 Pasajeros En Régimen De Transporte Y De Crucero,Marzo_2024 Pasajeros En Régimen De Transporte Y De Crucero,Marzo_2023 Pasajeros En Régimen De Transporte,Marzo_2024 Pasajeros En Régimen De Transporte,Marzo_2023 Pasajeros De Crucero,Marzo_2024 Pasajeros De Crucero,Marzo_2023 Automóviles En Régimen De Pasaje,Marzo_2024 Automóviles En Régimen De Pasaje,Marzo_2023 Automóviles En Régimen De Mercancía,Marzo_2024 Automóviles En Régimen De Mercancía
1,A Coruña,591403,863302,544458,279003,80350,50451,0,0,2442.947,1445.893,7792,7032,3394,2081,0,0,318609,7920,0,0,0,0,0,0,0.0,0.0,0.0,0.0,0.00,0.0,0.00,0.0,86,98,1659967,1843269,4,5,10565,13679,0,0,10565,13679,0,0,0,0
2,Alicante,6504,9103,276103,220934,107639,110251,96319,105093,0,0,1509,1554,204,79,0,0,0,1901,0,1901,4804,406,214,5,14534.0,16216.5,0.0,203.0,13380.25,13920.5,1153.75,2093.0,57,67,745037,857634,3,2,13212,9669,7243,7215,5969,2454,1687,3133,95,243

## Abril

In [27]:
ruta_abril = os.path.join('C:/Users/Encarni/Desktop/TFM/Tablas_descargadas/Modificados_pestaña/2024/4_abril_2024.xlsx')
df_abril = pd.read_excel(ruta_abril)
display(df_abril)

,Autoridad Portuaria,Abril Graneles Líquidos,Unnamed: 2,Acumulado desde Abril Graneles Líquidos,Unnamed: 4,Unnamed: 5,Abril Graneles Sólidos,Unnamed: 7,Acumulado desde Abril Graneles Sólidos,Unnamed: 9,Unnamed: 10,Abril Mercancía General,Unnamed: 12,Acumulado desde Abril Mercancía General,Unnamed: 14,Unnamed: 15,Abril Mercancía general en contenedores,Unnamed: 17,Acumulado desde Abril Mercancía General en contenedores,Unnamed: 19,Unnamed: 20,Abril Pesca,Unnamed: 22,Acumulado desde Abril Pesca,Unnamed: 24,Unnamed: 25,Abril Avituallamiento,Unnamed: 27,Acumulado desde Abril Avituallamiento,Unnamed: 29,Unnamed: 30,Abril Avituallamiento de combustibles líquidos,Unnamed: 32,Acumulado desde Abril Avituallamiento de combustibles líquidos,Unnamed: 34,Unnamed: 35,Abril Tráfico interior,Unnamed: 37,Acumulado desde Abril Tráfico interior,Unnamed: 39,Unnamed: 40,Abril Mercancías en tránsito,Unnamed: 42,Acumulado desde Abril Mercancías en tránsito,Unnamed: 44,Unnamed: 45,Abril Mercancías en tránsito en contenedores,Unnamed: 47,Acumulado desde Abril Mercancías en tránsito en contenedores,Unnamed: 49,Unnamed: 50,Abril Tráfico Ro-Ro,Unnamed: 52,Acumulado desde Abril Tráfico Ro-Ro,Unnamed: 54,Unnamed: 55,Abril Unidades de transporte intermodal Ro-Ro UTIS,Unnamed: 57,Acumulado desde Abril Unidades de transporte intermodal Ro-Ro UTIS,Unnamed: 59,Unnamed: 60,Abril Contenedores TEUS,Unnamed: 62,Acumulado desde Abril Contenedores TEUS,Unnamed: 64,Unnamed: 65,Abril Contenedores en tránsito TEUS,Unnamed: 67,Acumulado desde Abril Contenedores en tránsito TEUS,Unnamed: 69,Unnamed: 70,Abril Contenedores entrada-salida nacional TEUS,Unnamed: 72,Acumulado desde Abril Contenedores entrada-salida nacional TEUS,Unnamed: 74,Unnamed: 75,Abril Contenedores entrada-salida exterior TEUS,Unnamed: 77,Acumulado desde Abril Contenedores entrada-salida exterior TEUS,Unnamed: 79,Unnamed: 80,Abril Buques mercantes (Número),Unnamed: 82,Acumulado desde Abril Buques mercantes (Número),Unnamed: 84,Unnamed: 85,Abril Buques mercantes (G.T.),Unnamed: 87,Acumulado desde Abril Buques mercantes (G.T.),Unnamed: 89,Unnamed: 90,Abril Buques de crucero (Número),Unnamed: 92,Acumulado desde Abril Buques de crucero (Número),Unnamed: 94,Unnamed: 95,Abril Pasajeros en régimen de transporte y de crucero (Número),Unnamed: 97,Acumulado desde Abril Pasajeros en régimen de transporte y de crucero (Número),Unnamed: 99,Unnamed: 100,Abril Pasajeros en régimen de transporte (Número),Unnamed: 102,Acumulado desde Abril Pasajeros en régimen de transporte (Número),Unnamed: 104,Unnamed: 105,Abril Pasajeros de crucero (Número),Unnamed: 107,Acumulado desde Abril Pasajeros de crucero (Número),Unnamed: 109,Unnamed: 110,Abril Automóviles en régimen de pasaje (Unidades),Unnamed: 112,Acumulado desde Abril Automóviles en régimen de pasaje (Unidades),Unnamed: 114,Unnamed: 115,Abril Automóviles en régimen de mercancía (Unidades),Unnamed: 117,Acumulado desde Abril Automóviles en régimen de mercancía (Unidades),Unnamed: 119,Unnamed: 120
0,NaN,2023 t,2024 t,2023 t,2024 t,Var. (%),2023 t,2024 t,2023 t,2024 t,Var. (%),2023 t,2024 t,2023 t,2024 t,Var. (%),2023 t,2024 t,2023 t,2024 t,Var. (%),2023 t,2024 t,2023 t,2024 t,Var. (%),2023 t,2024 t,2023 t,2024 t,Var. (%),2023 t,2024 t,2023 t,2024 t,Var. (%),2023 t,2024 t,2023 t,2024 t,Var. (%),2023 t,2024 t,2023 t,2024 t,Var. (%),2023 t,2024 t,2023 t,2024 t,Var. (%),2023 t,2024 t,2023 t,2024 t,Var. (%),2023,2024,2023,2024,Var. (%),2023.00,2024.00,2023.00,2024.00,Var. (%),2023.00,2024.00,2023.0,2024.00,Var. (%),2023.00,2024.00,2023.00,2024.00,Var. (%),2023.00,2024.00,2023.00,2024.00,Var. (%),2023,2024,2023,2024,Var. (%),2023 GT,2024 GT,2023 GT,2024 GT,Var. (%),2023,2024,2023,2024,Var. (%),2023,2024,2023,2024,Var. (%),2023,2024,2023,2024,Var. (%),2023,2024,2023,2024,Var. (%),2023,2024,2023,2024,Var. (%),2023,2024,2023,2024,Var. (%)
1,A Coruña,548746,1021334,2712174,3351746,23.581525,482784,439120,2091072,1412871,-32.433173,56369,77264,235039,171799,-26.906173,43,14,109,14,-87.155963,2122.334,1716.183,7153.653,5313.002,-25.730225,3001,2996,16533,15061,-8.903405,2239,2034,9720,7670,-21.090535,0,0,0,0,,172519,98438,1075308,155299,-85.557719,0,0,0,0,,0,0,0,0,,0,0,0,0,,3.00,2.00,9.00,2.00,-77.777778,0.00,0.00,0.0,0.00,,0.00,0.00,0.00,0.00,,3.00,2.00,9.00,2.00,-77.777778,103,119,366,368,0.546448,2292395,3316704,6957052,7901359,13.573378,14,16,22,27,22.727273,27030,47166,44179,74263,68.095702,0,0,0,0,,27030,47166,44179,74263,68.095702,0,0,0,0,,0,0,0,0,
2,Alicante,1,2188,11958,22146,85.198194,115313,193671,718583,699307,-2.682502,95672,87769,396248,376879,-4.8881,92492,84155,367791,355681,-3.292631,0,0,0,0,,2751,1656,7571,6403,-15.427288,123,181,696,417,-40.086207,0,0,0,0,,3908,1901,5008,4679,-6.569489,3908,1901,5008,4679,-6.569489,228,1604,9913,9127,-7.928982,0,0,400,237,-40.75,13645.25,13062.75,56289.75,54174.75,-3.757345,437.50,203.00,547.0,500.00,-8.592322,11838.00,11700.25,48743.25,46347.75,-4.914527,1369.75,1159.50,6999.50,7327.00,4.678906,56,70,224,246,9.821429,1042086,2089152,3581064,4159544,16.153858,9,17,20,20,0,23635,40447,75355,70095,-6.980293,11055,8181,36215,33214,-8.286622,12580,32266,39140,36881,-5.771589,3120,3197,9262,12012,29.691211,117,228,432,763,76.62037
3,Almería,0,18288,8227,63268,669.028808,370541,405453,1352379,1111422,-17.817269,78309,129640,354204,451909,27.584386,16167,27257,52286,79660,52.354359,211.811,396.221,653.763,878.168,34.32513,4852,5869,21043,21859,3.877774,2843,3234,11927,10337,-13.331098,0,0,0,0,,28,0,43,0,-100,28,0,43,0,-100,48102,80829,227209,276514,21.700285,2565,4190,11874,14443,21.635506,1896.00,1690.50,5583.00,4867.25,-12.820168,14.00,0.00,17.0,0.00,-100,1281.00,382.00,3439.00,1299.75,-62.205583,601.00,1308.50,2127.00,3567.50,67.724495,124,140,475,525,10.526316,2085732,2327011,8008916,8488984,5.994169,4,3,4,3,-25,26333,28669,111676,123421,10.517031,25678,27573,111021,122325,10.181857,655,1096,655,1096,67.328244,8721,8555,33620,37120,10.41047,174,1142,672,1829,172.172619
4,Avilés,45014,74314,229014,220694,-3.632966,227675,249775,967044,792165,-18.083872,71541,102711,369729,397050,7.389466,0,0,0,0,,2012.55,1504.075,4185.798,3755.986,-10.268341,3245,3373,16026,12491,-22.057906,787,753,5048,4149,-17.809033,0,0,0,0,,0,0,0,0,,0,0,0,0,,0,0,0,0,,0,0,0,0,,0.00,0.00,0.00,0.00,,0.00,0.00,0.0,0.00,,0.00,0.00,0.00,0.00,,0.00,0.00,0.00,0.00,,62,70,254,246,-3.149606,482399,579821,1974387,1966490,-0.399972,0,0,0,0,,0,0,0,0,,0,0,0,0,,0,0,0,0,,0,0,0,0,,0,0,0,0,
5,Bahía de Algeciras,2359749,2392855,8959010,9987525,11.480231,36596,2314,226836,68910,-69.621224,6184103,6202074,23498475,23419160,-0.337533,4952620,5127554,18407105,19139437,3.978529,43.229,108.71,193.611,308.936,59.565314,308727,342479,1137363,1253512,10.212131,295580,330301,1082494,1199536,10.812254,286282,337641,1094102,1228612,12.294101,5660961,5657520,20849688,21580388,3.504609,4417931,4600562,16372422,17137383,4.672253,1221567,1085163,5061105,4302145,-14.995935,40664,45875,167792,181894,8.404453,409915.00,412658.00,1529015.00,1584083.00,3.601534,345933.00,358038.00,1279223.0,1352333.00,5.715188,0.00,0.00,8.00,14.00,75,63982.00,54620.00,249784.00,231736.00,-7.225443,2220,2405,8715,9332,7.079748,41307060,46474631,162893099,181048581,11.145642,0,0,0,0,,327554,346545,1193243,1316332,10.315502,327554,346545,1193243,1316332,10.315502,0,0,0,0,,65612,74171,243460,284295,16.772776,312,385,1140,1388,21.754386
6,Bahía de Cádiz,50715,42600,502483,161265,-67.906377,139223,152369,587614,613106,4.338222,161301,195263,673265,745394,10.713315,113089,138220,467979,521614,11.460984,1011.52,1106.938,3605.426,3395.587,-5.820089,6157,7196,32285,31598,-2.127923,2888,1906,9083,10673,17.50523,0,0,0,0,,74211,65475,561451,226031,-59.741634,19012,22196,72044,71422,-0.863361,62151,69951,271862,275080,1.183689,1931,2279,8208,8891,8.32115,14077.50,18096.25,61347.50,69989.00,14.086149,1638.25,1872.50,6332.0,6577.50,3.877132,10507.00,13384.75,47243.50,53062.00,12.31598,1932.25,2839.00,7772.00,10349.50,33.163922,129,128,489,450,-7.97546,3921621,3987028,11377025,9998806,-12.114054,51,40,94,71,-24.468085,65643,64693,144951,131653,-9.174135,1690,2601,6159,7406,20.246793,63953,62092,138792,124247,-10.479711,1044,1643,3739,4591,22.786841,1389,9836,6869,14104,105.328287
7,Baleares,93106,111202,315017,420491,33.482003,31421,35730,139215,116428,-16.368207,1195478,1340891,4344844,4623896,6.422601,27975,25398,103754,100040,-3.579621,116.885,188.376,392.917,494.417,25.832428,10956,10488,22427,28995,29.286128,146,11,532,444,-16.541353,535,421,1722,960,-44.250871,997,1300,3671,3845,4.739853,2,0,2,0,-100,1182038,1336651,4310368,4586709,6.411077,56023,62871,204256,214006,4.773422,7800.00,7000.00,28826.00,26557.00,-7.871366,2.00,0.00,2.0,0.00,-100,7798.00,6998.00,28822.00,26555.00,-7.865519,0.00,2.00,2.00,2.00,0,3730,3712,11534,12518,8.531299,20759717,22128121,70616501,74098535,4.930907,58,71,102,116,13.72549,722105,665225,1658273,1690488,1.942684,586589,515411,1364150,1375573,0.837371,135516,149814,294123,314915,7.069151,111964,102757,273790,296877,8.432375,10089,13369,35854,44580,24.337591
8,Barcelona,1368012,1042996,4594805,4011300,-12.699233,352117,314063,1634339,1396997,-14.522201,3616465,4453149,14336438,16906320,17.925527,2675116,3429166,10731941,13139866,22.436994,108.168,235.408,427.668,692.47,61.917656,147345,149131,488026,458064,-6.139427,122363,126503,415746,391900,-5.735714,0,0,0,0,,1735684,2290086,6562972,9018188,37.410125,1261030,1839056,4951603,7191837,45.242601,965941,1015506,3707875,3815853,2.912126,34219,37159,130611,136779,4.72242,252905.00,338986.25,1026763.25,1290641.50,25.700009,101291.50,170591.00,403204.5,621626.50,54.171518,67899.50,82935.25,280487.25,311857.50,11.184198,83714.00,85460.00,343071.50,357149.50,4.103518,720,701,2666,2642,-0.900225,30541700,30767991,104565962,105659684,1.045964,79,79,157,144,-8.280255,400530,395390,915737,962832,5.142852,133110,117819,356225,365785,2.683697,267420,277571,559512,597047,6.708525,33502,30677,95795,100587,5.002349,69834,61709,266789,246334,-7.667108
9,Bilbao,1697306,1896200,6507733,7612275,16.972761,300970,416388,1292474,1253486,-3.01654,774441,749547,2696146,2654985,-1.526661,457699,425341,1736752,1659981,-4.420378,0,0,0,0,,11146,13330,41064,44210,7.661212,5796,6932,21541,23204,7.720162,0,0,0,0,,9574,18228,17116,30693,79.32344,9574,18228,16695,30693,83.845463,94966,126292,326468,320935,-1.694806,3597,4687,12739,11681,-8.305204,42999.75,36287.00,166838.00,150046.50,-10.064554,513.75,1158.00,1027.5,2125.50,106.861314,3016.25,1570.75,15033.00,6363.50,-57.669793,39469.75,33558.25,150777.50,141557.50,-6.114971,233,244,854,837,-1.990632,5272104,5608259,16730287,17322607,3.540405,7,6,7,6,-14.285714,18704,31118,27571,37564,36.244605,11409,11962,20276,18408,-9.212862,7295,19156,7295,19156,162.590816,4966,5773,8520,8873,4.143192,14822,27137,27044,37256,37.760686
10,Cartagena,2794322,2357400,9851548,9164308,-6.97596,629526,647973,2747290,2919669,6.274511,70812,95921,310031,294484,-5.01466,48104,52645,183941,188084,2.252353,34.21,26.678,71.338,94.393,32.317979,21267,20411,63472,58162,-8.365894,1144,930,3873,3789,-2.168861,0,0,0,0,,0,1916,380640,84862,-77.705443,0,0,29,0,-100,3355,0,10663,2460,-76.92957,0,0,0,0,,4206.50,5318.00,13727.25,16221.00,18.166421,0.00,0.00,2.0,0.00,-100,1432.25,1772.00,3257.25,4476.00,37.416532,2774.25,3546.00,10468.00,11745.00,12.199083,202,203,677,677,0,4806803,4765533,15781217,14609691,-7.423547,21,26,33,30,-9.090909,17919,21955,34810,27049,-22.295317,0,0,0,0,,17919,21955,34810,27049,-22.295317,0,0,0,0,,24,4,35,2010,5642.857143
11,Castellón,1068669,744729,3225745,2940405,-8.845709,515772,799387,2216654,2243137,1.194729,119760,83019,408151,328196,-19.589564,114425,82071,378288,320527,-15.269054,241.399,99.509,807.637,916.61,13.492819,2013,3034,8768,9562,9.055657,0,0,0,0,,0,0,0,0,,1898,66,4442,9877,122.354795,1898,66,4442,5877,32.305268,25047,0,61626,17304,-71.920942,0,0,17,0,-100,9313.00,5634.25,27041.00,22745.50,-15.885137,381.00,8.00,796.0,304.00,-61.809045,980.00,711.25,2112.00,2378.00,12.594697,7952.00,4915.00,24133.00,20063.50,-16.862802,123,122,454,432,-4.845815,1860360,1771209,6443174,6199535,-3.781351,0,1,0,1,,0,743,0,743,,0,0,0,0,,0,743,0,743,,0,0,0,0,,204,102,445,179,-59.775281
12,Ceuta,91102,21761,246765,160656,-34.895143,1426,26,3826,1426,-62.728698,38098,46670,168160,183715,9.250119,4962,5792,21827,23482,7.582352,0.453,0,0.961,0,-100,39911,46627,204401,154830,-24.251838,37723,44595,197880,147346,-25.5377,0,0,0,0,,0,0,0,0,,0,0,0,0,,37837,45955,166599,181144,8.730545,2156,2740,9831,10845,10.314312,402.00,457.00,1832.50,1841.00,0.463847,0.00,0.00,0.0,0.00,,393.00,439.00,1777.50,1766.00,-0.646976,9.00,18.00,55.00,75.00,36.363636,787,831,3139,3230,2.899012,5596153,7304888,23290570,22821942,-2.012093,3,1,11,1,-90.909091,148305,143082,533824,532262,-0.292606,142485,142968,514181,532148,3.494295,5820,114,19643,114,-99.419641,33978,36246,120529,131576,9.165429,94,137,445,732,64.494382
13,Ferrol-San Cibrao,447029,175605,1691763,660647,-60.949199,242034,301069,1118173,1426659,27.588396,115599,73011,448079,235471,-47.448776,44732,10320,182709,39557,-78.349726,19.407,9.975,65.734,35.489,-46.011197,1383,1547,4533,3895,-14.074564,321,877,2137,2045,-4.305101,68,0,68,0,-100,70301,2160,234758,329853,40.507672,0,185,0,673,,2049,1355,6132,4176,-31.898239,0,7,21,12,-42.857143,3214.50,1116.00,15160.50,3961.50,-73.869595,0.00,39.50,0.0,127.75,,740.00,159.50,4101.50,592.75,-85.54797,2474.50,917.00,11059.00,3241.00,-70.693553,94,73,348,269,-22.701149,1638109,870274,6029988,3670590,-39.12774,3,2,4,3,-25,1533,2199,2282,3163,38.606486,0,0,0,0,,1533,2199,2282,3163,38.606486,0,0,0,0,,66,0,126,0,-100
14,Gijón,94643,168327,378035,517219,36.817755,2023648,972529,6340841,3746262,-40.918531,168477,165191,514321,659666,28.259589,55035,104967,224544,366487,63.213891,1117.357,1408.73,3064.667,2639.551,-13.871523,3642,0,11065,0,-100,3642,0,11065,0,-100,0,0,0,0,,987322,81812,2788173,631317,-77.357323,333,3,616,11,-98.214286,0,0,0,0,,0,0,0,0,,4450.00,8254.00,16842.00,26722.00,58.662867,18.00,1.00,89.0,5.00,-94.382022,385.00,486.00,2744.00,1844.00,-32.798834,4047.00,7767.00,14009.00,24873.00,77.550146,115,103,418,359,-14.114833,2169686,1905753,7391482,6003444,-18.778886,3,3,4,3,-25,2205,4662,3190,4662,46.144201,0,0,0,0,,2205,4662,3190,4662,46.144201,0,0,0,0,,3,1,4,6,50
15,Huelva,1806270,2241857,7402445,8336468,12.617763,366861,504866,1692838,1745221,3.094389,110182,173675,411357,620766,50.906877,44552,69734,177866,274768,54.480339,12.869,11.263,59.321,38.454,-35.176413,13898,2615,46548,19765,-57.538455,11574,488,38224,11562,-69.751988,5088,0,18107,29796,64.555144,129182,227082,560479,923382,64.748724,0,21618,6,67822,1130266.666667,58157,61892,217576,240478,10.525977,2884,2698,10822,11640,7.558677,6476.50,8709.50,24939.50,36292.50,45.522164,0.00,1222.75,1.0,4651.00,465000,5639.50,6495.00,21757.50,27785.25,27.70424,837.00,991.75,3181.00,3856.25,21.227601,165,198,640,770,20.3125,3342462,3928512,12971858,14316292,10.364236,0,2,0,2,,5511,4580,18394,17933,-2.506252,5511,4526,18394,17879,-2.799826,0,54,0,54,,3382,2794,11228,10694,-4.755967,1397,3654,3798,7631,100.921538
16,Las Palmas,628616,657160,2655932,2694749,1.461521,18454,43494,128083,121930,-4.803916,1444956,1582956,5677461,6372338,12.239221,1069177,1164137,4138217,4779527,15.497254,74.763,94.657,194.927,156.179,-19.878211,201358,277268,845259,975675,15.429117,176475,255262,731298,872656,19.32974,0,0,0,6,,1005142,1022904,3983997,4341011,8.961202,735395,791977,2739838,3325699,21.383053,372181,426465,1535756,1643022,6.984573,25825,28676,107914,111347,3.181237,96418.00,102951.00,382269.00,431811.00,12.959984,51016.00,54466.00,193857.0,238192.00,22.869951,39986.00,42091.00,164523.00,167846.00,2.019778,5416.00,6394.00,23889.00,25773.00,7.886475,1041,1176,4197,4453,6.099595,22597579,28121334,97850858,108199083,10.575508,79,86,337,313,-7.121662,304636,294319,1263421,1331886,5.419017,151176,103439,455408,436119,-4.235543,153460,190880,808013,895767,10.860469,61789,47059,194464,189431,-2.58814,62118,25749,165950,112112,-32.442302
17,Málaga,13937,18072,34847,47649,36.737739,140446,130782,481308,540094,12.213801,79133,339665,272448,695273,155.194753,32144,307980,96512,487748,405.375497,13.745,7.186,40.16,69.765,73.717629,9983,10615,26866,25214,-6.149036,3591,2773,10446,11107,6.327781,0,0,0,0,,9086,291235,18651,458603,2358.865476,8151,286130,13484,406925,2917.835954,52077,33255,185240,202524,9.330598,2973,1936,10551,9618,-8.842764,6160.75,27618.25,14342.25,44952.25,213.425369,3911.50,25584.25,6574.0,37197.25,465.823699,641.25,773.00,3010.25,2415.00,-19.774105,1608.00,1261.00,4758.00,5340.00,12.23203,163,145,485,491,1.237113,4924933,6191505,13129979,16187090,23.283442,43,44,74,54,-27.027027,62565,77011,179757,161933,-9.915608,17996,17895,78913,84259,6.774549,44569,59116,100844,77674,-22.976082,3995,4107,15330,18497,20.658839,4683,4084,18591,45957,147.200258
18,Marín y Ría de Pontevedra,0,0,0,0,,75393,81644,296456,406017,36.956918,106228,119832,366714,380843,3.852866,36914,46139,157170,147559,-6.115035,173.499,163.289,827.047,665.139,-19.576638,1423,1632,5414,7481,38.178796,450,1093,2048,4468,118.164062,0,0,0,0,,92,0,500,732,46.4,92,0,500,192,-61.6,0,0,0,0,,0,0,0,0,,3164.75,4592.50,14083.75,15202.00,7.940002,46.00,0.00,250.0,12.00,-95.2,322.00,716.75,1425.00,1267.75,-11.035088,2796.75,3875.75,12408.75,13922.25,12.197038,48,49,148,169,14.189189,239447,302676,829552,1095480,32.056821,0,0,0,0,,0,0,0,0,,0,0,0,0,,0,0,0,0,,0,0,0,0,,3,17,22,198,800
19,Melilla,6318,3853,20372,20851,2.351266,1492,0,2991,0,-100,34252,41085,144709,149159,3.075137,3697,3398,14741,12735,-13.608303,0,0,0,0,,50,0,1902,106,-94.426919,0,0,0,0,,0,0,0,0,,0,0,0,0,,0,0,0,0,,34252,41085,144709,149159,3.075137,2167,2877,9416,9994,6.138488,505.00,472.00,2019.00,1853.50,-8.197127,0.00,0.00,0.0,0.00,,501.00,468.00,2002.00,1841.50,-8.016983,4.00,4.00,17.00,12.00,-29.411765,95,99,369,379,2.710027,2675389,2874211,8975082,10861145,21.014438,1,3,2,4,100,28726,36381,122522,143017,16.727608,28068,35100,121107,141148,16.548176,658,1281,1415,1869,32.084806,6734,9312,26567,35276,32.78127,211,165,733,11478,1465.893588
20,Motril,108471,97667,442351,435807,-1.479368,104321,61928,184052,291505,58.38187,48896,60361,199264,213412,7.100128,325,150,2014,812,-59.682224,44.942,64.436,193.952,265.619,36.950895,1887,2062,7520,7479,-0.545213,1482,1121,4142,4575,10.453887,2998,0,2998,0,-100,3058,0,42920,3619,-91.568034,0,0,0,0,,46000,52737,176706,183907,4.07513,1686,2121,6438,7615,18.282075,58.00,26.00,358.00,123.50,-65.502793,0.00,0.00,0.0,0.00,,0.00,0.00,0.00,0.00,,58.00,26.00,358.00,123.50,-65.502793,87,84,281,307,9.252669,1454607,1465163,4140570,4307120,4.022393,5,9,5,9,80,10384,17251,21541,39468,83.222692,4942,7970,16099,30187,87.508541,5442,9281,5442,9281,70.543918,1312,2572,3857,9605,149.027742,168,1539,1188,1557,31.060606
21,Pasaia,0,0,0,0,,63794,64008,294669,255104,-13.42693,209655,214223,844815,849992,0.612797,0,0,0,0,,1743.274,3361.326,8530.149,7649.498,-10.323981,2627,2273,8772,8932,1.823985,1487,686,4327,3352,-22.532933,0,0,0,0,,36,3008,5349,12048,125.238362,0,0,0,0,,46039,43666,204041,204131,0.044109,211,238,1075,1133,5.395349,0.00,0.00,0.00,0.00,,0.00,0.00,0.0,0.00,,0.00,0.00,0.00,0.00,,0.00,0.00,0.00,0.00,,78,83,305,289,-5.245902,606285,566891,2430966,2300175,-5.380207,2,1,2,1,-50,562,854,564,854,51.41844,0,0,0,0,,562,854,564,854,51.41844,0,0,0,0,,20667,16852,85748,84885,-1.006437

In [28]:
df_abril.columns.unique

<bound method Index.unique of Index(['Autoridad Portuaria', 'Abril Graneles Líquidos', 'Unnamed: 2',
       'Acumulado desde Abril Graneles Líquidos', 'Unnamed: 4', 'Unnamed: 5',
       'Abril Graneles Sólidos', 'Unnamed: 7',
       'Acumulado desde Abril Graneles Sólidos', 'Unnamed: 9',
       ...
       'Abril Automóviles en régimen de pasaje (Unidades)', 'Unnamed: 112',
       'Acumulado desde Abril Automóviles en régimen de pasaje (Unidades)',
       'Unnamed: 114', 'Unnamed: 115',
       'Abril Automóviles en régimen de mercancía (Unidades)', 'Unnamed: 117',
       'Acumulado desde Abril Automóviles en régimen de mercancía (Unidades)',
       'Unnamed: 119', 'Unnamed: 120'],
      dtype='object', length=121)>

In [29]:
df_abril = df_abril.drop(['Acumulado desde Abril Graneles Líquidos', 'Unnamed: 4', 'Unnamed: 5' ], axis=1)
df_abril = df_abril.drop(['Acumulado desde Abril Graneles Sólidos', 'Unnamed: 9', 'Unnamed: 10'], axis=1)
df_abril = df_abril.drop(['Acumulado desde Abril Mercancía General', 'Unnamed: 14', 'Unnamed: 15'], axis=1)
df_abril = df_abril.drop(['Acumulado desde Abril Mercancía General en contenedores', 'Unnamed: 19', 'Unnamed: 20'], axis=1)
df_abril = df_abril.drop(['Acumulado desde Abril Pesca', 'Unnamed: 24', 'Unnamed: 25'], axis=1)
df_abril = df_abril.drop(['Acumulado desde Abril Avituallamiento', 'Unnamed: 29', 'Unnamed: 30'], axis=1)
df_abril = df_abril.drop(['Acumulado desde Abril Avituallamiento de combustibles líquidos', 'Unnamed: 34', 'Unnamed: 35'], axis=1)
df_abril = df_abril.drop(['Acumulado desde Abril Tráfico interior', 'Unnamed: 39', 'Unnamed: 40'], axis=1)
df_abril = df_abril.drop(['Acumulado desde Abril Mercancías en tránsito', 'Unnamed: 44', 'Unnamed: 45'], axis=1)
df_abril = df_abril.drop(['Acumulado desde Abril Mercancías en tránsito en contenedores', 'Unnamed: 49', 'Unnamed: 50'], axis=1)
df_abril = df_abril.drop(['Acumulado desde Abril Tráfico Ro-Ro', 'Unnamed: 54', 'Unnamed: 55'], axis=1)
df_abril = df_abril.drop(['Acumulado desde Abril Unidades de transporte intermodal Ro-Ro UTIS', 'Unnamed: 59', 'Unnamed: 60'], axis=1)
df_abril = df_abril.drop(['Acumulado desde Abril Contenedores TEUS', 'Unnamed: 64', 'Unnamed: 65'], axis=1)
df_abril = df_abril.drop(['Acumulado desde Abril Contenedores en tránsito TEUS', 'Unnamed: 69', 'Unnamed: 70'], axis=1)
df_abril = df_abril.drop(['Acumulado desde Abril Contenedores entrada-salida nacional TEUS', 'Unnamed: 74', 'Unnamed: 75'], axis=1)
df_abril = df_abril.drop(['Acumulado desde Abril Contenedores entrada-salida exterior TEUS', 'Unnamed: 79', 'Unnamed: 80'], axis=1)
df_abril = df_abril.drop(['Acumulado desde Abril Buques mercantes (Número)', 'Unnamed: 84', 'Unnamed: 85'], axis=1)
df_abril = df_abril.drop(['Acumulado desde Abril Buques mercantes (G.T.)', 'Unnamed: 89', 'Unnamed: 90'], axis=1)
df_abril = df_abril.drop(['Acumulado desde Abril Buques de crucero (Número)', 'Unnamed: 94', 'Unnamed: 95'], axis=1)
df_abril = df_abril.drop(['Acumulado desde Abril Pasajeros en régimen de transporte y de crucero (Número)', 'Unnamed: 99', 'Unnamed: 100'], axis=1)
df_abril = df_abril.drop(['Acumulado desde Abril Pasajeros en régimen de transporte (Número)', 'Unnamed: 104', 'Unnamed: 105'], axis=1)
df_abril = df_abril.drop(['Acumulado desde Abril Pasajeros de crucero (Número)', 'Unnamed: 109', 'Unnamed: 110'], axis=1)
df_abril = df_abril.drop(['Acumulado desde Abril Automóviles en régimen de pasaje (Unidades)', 'Unnamed: 114', 'Unnamed: 115'], axis=1)
df_abril = df_abril.drop(['Acumulado desde Abril Automóviles en régimen de mercancía (Unidades)', 'Unnamed: 119', 'Unnamed: 120'], axis=1)

In [30]:
Renombrar_abril = {'Abril Graneles Líquidos': 'Abril_2023 t Graneles Líquidos', 'Unnamed: 2': 'Abril_2024 t Graneles Líquidos',
             'Abril Graneles Sólidos': 'Abril_2023 t Graneles Sólidos', 'Unnamed: 7': 'Abril_2024 t Graneles Sólidos',
             'Abril Mercancía General': 'Abril_2023 t Mercancía General', 'Unnamed: 12': 'Abril_2024 t Mercancía General',
             'Abril Mercancía general en contenedores': 'Abril_2023 t Mercancía General Contenedores', 'Unnamed: 17': 'Abril_2024 t Mercancía General Contenedores',
             'Abril Pesca': 'Abril_2023 t Pesca', 'Unnamed: 22': 'Abril_2024 t Pesca',
             'Abril Avituallamiento': 'Abril_2023 t Avituallamiento', 'Unnamed: 27': 'Abril_2024 t Avituallamiento',
             'Abril Avituallamiento de combustibles líquidos': 'Abril_2023 t Avituallamiento De Combustibles Líquidos', 'Unnamed: 32': 'Abril_2024 t Avituallamiento De Combustibles Líquidos',
             'Abril Tráfico interior': 'Abril_2023 t Tráfico Interior', 'Unnamed: 37': 'Abril_2024 t Tráfico Interior',
             'Abril Mercancías en tránsito': 'Abril_2023 t Mercancías En Tránsito', 'Unnamed: 42': 'Abril_2024 t Mercancías En Tránsito',
             'Abril Mercancías en tránsito en contenedores': 'Abril_2023 t Mercancías En Tránsito En Contenedores', 'Unnamed: 47': 'Abril_2024 t Mercancías En Tránsito En Contenedores',
             'Abril Tráfico Ro-Ro': 'Abril_2023 t Tráfico Ro-Ro', 'Unnamed: 52': 'Abril_2024 t Tráfico Ro-Ro',
             'Abril Unidades de transporte intermodal Ro-Ro UTIS': 'Abril_2023 UTIS Ro-Ro', 'Unnamed: 57': 'Abril_2024 UTIS Ro-Ro', 
             'Abril Contenedores TEUS': 'Abril_2023 TEUS Contenedores', 'Unnamed: 62': 'Abril_2024 TEUS Contenedores', 
             'Abril Contenedores en tránsito TEUS': 'Abril_2023 TEUS Contenedores En Tránsito', 'Unnamed: 67': 'Abril_2024 TEUS Contenedores En Tránsito',
             'Abril Contenedores entrada-salida nacional TEUS': 'Abril_2023 TEUS Contenedores Entrada-Salida Nacional', 'Unnamed: 72': 'Abril_2024 TEUS Contenedores Entrada-Salida Nacional',
             'Abril Contenedores entrada-salida exterior TEUS': 'Abril_2023 TEUS Contenedores Entrada-Salida Exterior', 'Unnamed: 77': 'Abril_2024 TEUS Contenedores Entrada-Salida Exterior',
             'Abril Buques mercantes (Número)': 'Abril_2023 Unidades Buques Mercantes', 'Unnamed: 82': 'Abril_2024 Unidades Buques Mercantes', 
             'Abril Buques mercantes (G.T.)': 'Abril_2023 G.T. Buques Mercantes', 'Unnamed: 87': 'Abril_2024 G.T. Buques Mercantes',
             'Abril Buques de crucero (Número)': 'Abril_2023 Unidades Buques De Crucero', 'Unnamed: 92': 'Abril_2024 Unidades Buques De Crucero',
             'Abril Pasajeros en régimen de transporte y de crucero (Número)': 'Abril_2023 Pasajeros En Régimen De Transporte Y De Crucero', 'Unnamed: 97': 'Abril_2024 Pasajeros En Régimen De Transporte Y De Crucero',
             'Abril Pasajeros en régimen de transporte (Número)': 'Abril_2023 Pasajeros En Régimen De Transporte', 'Unnamed: 102': 'Abril_2024 Pasajeros En Régimen De Transporte',
             'Abril Pasajeros de crucero (Número)': 'Abril_2023 Pasajeros De Crucero', 'Unnamed: 107': 'Abril_2024 Pasajeros De Crucero',
             'Abril Automóviles en régimen de pasaje (Unidades)': 'Abril_2023 Automóviles En Régimen De Pasaje', 'Unnamed: 112': 'Abril_2024 Automóviles En Régimen De Pasaje',
             'Abril Automóviles en régimen de mercancía (Unidades)': 'Abril_2023 Automóviles En Régimen De Mercancía', 'Unnamed: 117': 'Abril_2024 Automóviles En Régimen De Mercancía'}

In [31]:
df_abril = df_abril.drop(0, axis=0)

In [32]:
df_abril = df_abril.rename(columns=Renombrar_abril)

In [33]:
df_abril.head()

,Autoridad Portuaria,Abril_2023 t Graneles Líquidos,Abril_2024 t Graneles Líquidos,Abril_2023 t Graneles Sólidos,Abril_2024 t Graneles Sólidos,Abril_2023 t Mercancía General,Abril_2024 t Mercancía General,Abril_2023 t Mercancía General Contenedores,Abril_2024 t Mercancía General Contenedores,Abril_2023 t Pesca,Abril_2024 t Pesca,Abril_2023 t Avituallamiento,Abril_2024 t Avituallamiento,Abril_2023 t Avituallamiento De Combustibles Líquidos,Abril_2024 t Avituallamiento De Combustibles Líquidos,Abril_2023 t Tráfico Interior,Abril_2024 t Tráfico Interior,Abril_2023 t Mercancías En Tránsito,Abril_2024 t Mercancías En Tránsito,Abril_2023 t Mercancías En Tránsito En Contenedores,Abril_2024 t Mercancías En Tránsito En Contenedores,Abril_2023 t Tráfico Ro-Ro,Abril_2024 t Tráfico Ro-Ro,Abril_2023 UTIS Ro-Ro,Abril_2024 UTIS Ro-Ro,Abril_2023 TEUS Contenedores,Abril_2024 TEUS Contenedores,Abril_2023 TEUS Contenedores En Tránsito,Abril_2024 TEUS Contenedores En Tránsito,Abril_2023 TEUS Contenedores Entrada-Salida Nacional,Abril_2024 TEUS Contenedores Entrada-Salida Nacional,Abril_2023 TEUS Contenedores Entrada-Salida Exterior,Abril_2024 TEUS Contenedores Entrada-Salida Exterior,Abril_2023 Unidades Buques Mercantes,Abril_2024 Unidades Buques Mercantes,Abril_2023 G.T. Buques Mercantes,Abril_2024 G.T. Buques Mercantes,Abril_2023 Unidades Buques De Crucero,Abril_2024 Unidades Buques De Crucero,Abril_2023 Pasajeros En Régimen De Transporte Y De Crucero,Abril_2024 Pasajeros En Régimen De Transporte Y De Crucero,Abril_2023 Pasajeros En Régimen De Transporte,Abril_2024 Pasajeros En Régimen De Transporte,Abril_2023 Pasajeros De Crucero,Abril_2024 Pasajeros De Crucero,Abril_2023 Automóviles En Régimen De Pasaje,Abril_2024 Automóviles En Régimen De Pasaje,Abril_2023 Automóviles En Régimen De Mercancía,Abril_2024 Automóviles En Régimen De Mercancía
1,A Coruña,548746,1021334,482784,439120,56369,77264,43,14,2122.334,1716.183,3001,2996,2239,2034,0,0,172519,98438,0,0,0,0,0,0,3.00,2.00,0.0,0.0,0.0,0.00,3.00,2.0,103,119,2292395,3316704,14,16,27030,47166,0,0,27030,47166,0,0,0,0
2,Alicante,1,2188,115313,193671,95672,87769,92492,84155,0,0,2751,1656,123,181,0,0,3908,1901,3908,1901,228,1604,0,0,13645.25,13062.75,437.5,203.0,11838.0,11700.25,1369.75,1159.5,56,70,1042086,2089152,9,17,23635,40447,11055,8181,12580,32266,3120,3197,117,228
3,Almería,0,18288,370541,405453,78309,129640,16167,27257,211.811,396.221,4852,5869,2843,3234,0,0,28,0,28,0,48102,80829,2565,4190,1896.00,1690.50,14.0,0.0,1281.0,382.00,601.00,1308.5,124,140,2085732,2327011,4,3,26333,28669,25678,27573,655,1096,8721,8555,174,1142
4,Avilés,45014,74314,227675,249775,71541,102711,0,0,2012.55,1504.075,3245,3373,787,753,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.0,0.0,0.0,0.00,0.00,0.0,62,70,482399,579821,0,0,0,0,0,0,0,0,0,0,0,0
5,Bahía de Algeciras,2359749,2392855,36596,2314,6184103,6202074,4952620,5127554,43.229,108.71,308727,342479,295580,330301,286282,337641,5660961,5657520,4417931,4600562,1221567,1085163,40664,45875,409915.00,412658.00,345933.0,358038.0,0.0,0.00,63982.00,54620.0,2220,2405,41307060,46474631,0,0,327554,346545,327554,346545,0,0,65612,74171,312,385

# Unión de todas las tablas

In [34]:
df_final = df_enero.merge(df_febrero, on='Autoridad Portuaria')

In [35]:
df_final_1 = df_final.merge(df_marzo, on='Autoridad Portuaria')

In [36]:
df_final_2 = df_final_1.merge(df_abril, on='Autoridad Portuaria')

In [37]:
df_final_2

,Autoridad Portuaria,Enero_2023 t Graneles Líquidos,Enero_2024 t Graneles Líquidos,Enero_2023 t Graneles Sólidos,Enero_2024 t Graneles Sólidos,Enero_2023 t Mercancía General,Enero_2024 t Mercancía General,Enero_2023 t Mercancía General Contenedores,Enero_2024 t Mercancía General Contenedores,Enero_2023 t Pesca,Enero_2024 t Pesca,Enero_2023 t Avituallamiento,Enero_2024 t Avituallamiento,Enero_2023 t Avituallamiento De Combustibles Líquidos,Enero_2024 t Avituallamiento De Combustibles Líquidos,Enero_2023 t Tráfico Interior,Enero_2024 t Tráfico Interior,Enero_2023 t Mercancías En Tránsito,Enero_2024 t Mercancías En Tránsito,Enero_2023 t Mercancías En Tránsito En Contenedores,Enero_2024 t Mercancías En Tránsito En Contenedores,Enero_2023 t Tráfico Ro-Ro,Enero_2024 t Tráfico Ro-Ro,Enero_2023 UTIS Ro-Ro,Enero_2024 UTIS Ro-Ro,Enero_2023 TEUS Contenedores,Enero_2024 TEUS Contenedores,Enero_2023 TEUS Contenedores En Tránsito,Enero_2024 TEUS Contenedores En Tránsito,Enero_2023 TEUS Contenedores Entrada-Salida Nacional,Enero_2024 TEUS Contenedores Entrada-Salida Nacional,Enero_2023 TEUS Contenedores Entrada-Salida Exterior,Enero_2024 TEUS Contenedores Entrada-Salida Exterior,Enero_2023 Unidades Buques Mercantes,Enero_2024 Unidades Buques Mercantes,Enero_2023 G.T. Buques Mercantes,Enero_2024 G.T. Buques Mercantes,Enero_2023 Unidades Buques De Crucero,Enero_2024 Unidades Buques De Crucero,Enero_2023 Pasajeros En Régimen De Transporte Y De Crucero,Enero_2024 Pasajeros En Régimen De Transporte Y De Crucero,Enero_2023 Pasajeros En Régimen De Transporte,Enero_2024 Pasajeros En Régimen De Transporte,Enero_2023 Pasajeros De Crucero,Enero_2024 Pasajeros De Crucero,Enero_2023 Automóviles En Régimen De Pasaje,Enero_2024 Automóviles En Régimen De Pasaje,Enero_2023 Automóviles En Régimen De Mercancía,Enero_2024 Automóviles En Régimen De Mercancía,Febrero_2023 t Graneles Líquidos,Febrero_2024 t Graneles Líquidos,Febrero_2023 t Graneles Sólidos,Febrero_2024 t Graneles Sólidos,Febrero Mercancía General,Febrero_2024 t Mercancía General,Febrero_2023 t Mercancía General Contenedores,Febrero_2024 t Mercancía General Contenedores,Febrero_2023 t Pesca,Febrero_2024 t Pesca,Febrero_2023 t Avituallamiento,Febrero_2024 t Avituallamiento,Febrero_2023 t Avituallamiento De Combustibles Líquidos,Febrero_2024 t Avituallamiento De Combustibles Líquidos,Febrero_2023 t Tráfico Interior,Febrero_2024 t Tráfico Interior,Febrero_2023 t Mercancías En Tránsito,Febrero_2024 t Mercancías En Tránsito,Febrero_2023 t Mercancías En Tránsito En Contenedores,Febrero_2024 t Mercancías En Tránsito En Contenedores,Febrero_2023 t Tráfico Ro-Ro,Febrero_2024 t Tráfico Ro-Ro,Febrero Unidades de transporte intermodal Ro-Ro UTIS,Febrero_2024 UTIS Ro-Ro,Febrero_2023 TEUS Contenedores,Febrero_2024 TEUS Contenedores,Febrero_2023 TEUS Contenedores En Tránsito,Febrero_2024 TEUS Contenedores En Tránsito,Febrero_2023 TEUS Contenedores Entrada-Salida Nacional,Febrero_2024 TEUS Contenedores Entrada-Salida Nacional,Febrero_2023 TEUS Contenedores Entrada-Salida Exterior,Febrero_2024 TEUS Contenedores Entrada-Salida Exterior,Febrero_2023 Unidades Buques Mercantes,Febrero_2024 Unidades Buques Mercantes,Febrero_2023 G.T. Buques Mercantes,Febrero_2024 G.T. Buques Mercantes,Febrero_2023 Unidades Buques De Crucero,Febrero_2024 Unidades Buques De Crucero,Febrero_2023 Pasajeros En Régimen De Transporte Y De Crucero,Febrero_2024 Pasajeros En Régimen De Transporte Y De Crucero,Febrero_2023 Pasajeros En Régimen De Transporte,Febrero_2024 Pasajeros En Régimen De Transporte,Febrero_2023 Pasajeros De Crucero,Febrero_2024 Pasajeros De Crucero,Febrero_2023 Automóviles En Régimen De Pasaje,Febrero_2024 Automóviles En Régimen De Pasaje,Febrero_2023 Automóviles En Régimen De Mercancía,Febrero_2024 Automóviles En Régimen De Mercancía,Marzo_2023 t Graneles Líquidos,Marzo_2024 t Graneles Líquidos,Marzo Graneles Sólidos,Marzo_2024 t Graneles Sólidos,Marzo_2023 t Mercancía General,Marzo_2024 t Mercancía General,Marzo_2023 t Mercancía General Contenedores,Marzo_2024 t Mercancía General Contenedores,Marzo_2023 t Pesca,Marzo_2024 t Pesca,Marzo_2023 t Avituallamiento,Marzo_2024 t Avituallamiento,Marzo_2023 t Avituallamiento De Combustibles Líquidos,Marzo_2024 t Avituallamiento De Combustibles Líquidos,Marzo_2023 t Tráfico Interior,Marzo_2024 t Tráfico Interior,Marzo_2023 t Mercancías En Tránsito,Marzo_2024 t Mercancías En Tránsito,Marzo_2023 t Mercancías En Tránsito En Contenedores,Marzo_2024 t Mercancías En Tránsito En Contenedores,Marzo_2023 t Tráfico Ro-Ro,Marzo_2024 t Tráfico Ro-Ro,Marzo_2023 UTIS Ro-Ro,Marzo_2024 UTIS Ro-Ro,Marzo_2023 TEUS Contenedores,Marzo_2024 TEUS Contenedores,Marzo_2023 TEUS Contenedores En Tránsito,Marzo_2024 TEUS Contenedores En Tránsito,Marzo_2023 TEUS Contenedores Entrada-Salida Nacional,Marzo_2024 TEUS Contenedores Entrada-Salida Nacional,Marzo_2023 TEUS Contenedores Entrada-Salida Exterior,Marzo_2024 TEUS Contenedores Entrada-Salida Exterior,Marzo_2023 Unidades Buques Mercantes,Marzo_2024 Unidades Buques Mercantes,Marzo_2023 G.T. Buques Mercantes,Marzo_2024 G.T. Buques Mercantes,Marzo_2023 Unidades Buques De Crucero,Marzo_2024 Unidades Buques De Crucero,Marzo_2023 Pasajeros En Régimen De Transporte Y De Crucero,Marzo_2024 Pasajeros En Régimen De Transporte Y De Crucero,Marzo_2023 Pasajeros En Régimen De Transporte,Marzo_2024 Pasajeros En Régimen De Transporte,Marzo_2023 Pasajeros De Crucero,Marzo_2024 Pasajeros De Crucero,Marzo_2023 Automóviles En Régimen De Pasaje,Marzo_2024 Automóviles En Régimen De Pasaje,Marzo_2023 Automóviles En Régimen De Mercancía,Marzo_2024 Automóviles En Régimen De Mercancía,Abril_2023 t Graneles Líquidos,Abril_2024 t Graneles Líquidos,Abril_2023 t Graneles Sólidos,Abril_2024 t Graneles Sólidos,Abril_2023 t Mercancía General,Abril_2024 t Mercancía General,Abril_2023 t Mercancía General Contenedores,Abril_2024 t Mercancía General Contenedores,Abril_2023 t Pesca,Abril_2024 t Pesca,Abril_2023 t Avituallamiento,Abril_2024 t Avituallamiento,Abril_2023 t Avituallamiento De Combustibles Líquidos,Abril_2024 t Avituallamiento De Combustibles Líquidos,Abril_2023 t Tráfico Interior,Abril_2024 t Tráfico Interior,Abril_2023 t Mercancías En Tránsito,Abril_2024 t Mercancías En Tránsito,Abril_2023 t Mercancías En Tránsito En Contenedores,Abril_2024 t Mercancías En Tránsito En Contenedores,Abril_2023 t Tráfico Ro-Ro,Abril_2024 t Tráfico Ro-Ro,Abril_2023 UTIS Ro-Ro,Abril_2024 UTIS Ro-Ro,Abril_2023 TEUS Contenedores,Abril_2024 TEUS Contenedores,Abril_2023 TEUS Contenedores En Tránsito,Abril_2024 TEUS Contenedores En Tránsito,Abril_2023 TEUS Contenedores Entrada-Salida Nacional,Abril_2024 TEUS Contenedores Entrada-Salida Nacional,Abril_2023 TEUS Contenedores Entrada-Salida Exterior,Abril_2024 TEUS Contenedores Entrada-Salida Exterior,Abril_2023 Unidades Buques Mercantes,Abril_2024 Unidades Buques Mercantes,Abril_2023 G.T. Buques Mercantes,Abril_2024 G.T. Buques Mercantes,Abril_2023 Unidades Buques De Crucero,Abril_2024 Unidades Buques De Crucero,Abril_2023 Pasajeros En Régimen De Transporte Y De Crucero,Abril_2024 Pasajeros En Régimen De Transporte Y De Crucero,Abril_2023 Pasajeros En Régimen De Transporte,Abril_2024 Pasajeros En Régimen De Transporte,Abril_2023 Pasajeros De Crucero,Abril_2024 Pasajeros De Crucero,Abril_2023 Automóviles En Régimen De Pasaje,Abril_2024 Automóviles En Régimen De Pasaje,Abril_2023 Automóviles En Régimen De Mercancía,Abril_2024 Automóviles En Régimen De Mercancía
0,A Coruña,676655,719906,521447,406133,40997,29789,66,0,1202.998,1148.912,2027,2903,1488,2245,0,0,268394,41024,0,0,0,0,0,0,6.00,0.00,0.00,0.00,0.00,0.00,6.00,0.00,81,81,1458841,1556239,4,4,6584,9704,0,0,6584,9704,0,0,0,0,895370,747204,542383,288615,57323,14295,0,0,1385.374,1002.014,3713,2130,2599,1310,0,0,315786,7917,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,96,70,1545849,1185147,0,2,0,3714,0,0,0,3714,0,0,0,0,591403,863302,544458,279003,80350,50451,0,0,2442.947,1445.893,7792,7032,3394,2081,0,0,318609,7920,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,86,98,1659967,1843269,4,5,10565,13679,0,0,10565,13679,0,0,0,0,548746,1021334,482784,439120,56369,77264,43,14,2122.334,1716.183,3001,2996,2239,2034,0,0,172519,98438,0,0,0,0,0,0,3.00,2.00,0.00,0.00,0.00,0.00,3.00,2.00,103,119,2292395,3316704,14,16,27030,47166,0,0,27030,47166,0,0,0,0
1,Alicante,5453,9007,191759,109123,96205,86149,89346,77281,0,0,1864,881,183,55,0,0,1100,297,1100,297,4830,6210,186,232,14253.75,10654.75,109.50,38.00,11790.50,8703.50,2353.75,1913.25,58,54,977692,548180,4,1,20175,8151,9362,5990,10813,2161,2517,1580,78,51,0,1848,135408,175579,96732,92710,89634,89152,0,0,1447,2312,186,102,0,0,0,580,0,580,51,907,0,0,13856.75,14240.75,0.00,56.00,11734.50,12023.50,2122.25,2161.25,53,55,816249,664578,4,0,18333,11828,8555,11828,9778,0,1938,4102,142,241,6504,9103,276103,220934,107639,110251,96319,105093,0,0,1509,1554,204,79,0,0,0,1901,0,1901,4804,406,214,5,14534.00,16216.50,0.00,203.00,13380.25,13920.50,1153.75,2093.00,57,67,745037,857634,3,2,13212,9669,7243,7215,5969,2454,1687,3133,95,243,1,2188,115313,193671,95672,87769,92492,84155,0,0,2751,1656,123,181,0,0,3908,1901,3908,1901,228,1604,0,0,13645.25,13062.75,437.50,203.00,11838.00,11700.25,1369.75,1159.50,56,70,1042086,2089152,9,17,23635,40447,11055,8181,12580,32266,3120,3197,117,228
2,Almería,4538,18511,299084,256126,74717,109347,11672,15607,186.172,228.505,5207,6088,2983,2622,0,0,2,0,2,0,49520,63344,2493,3102,1293.50,1116.75,1.00,0.00,746.00,457.75,546.50,659.00,112,134,1897714,2131887,0,0,35434,40825,35434,40825,0,0,9707,11445,170,239,3689,19338,313763,256103,97314,116222,9285,18881,145.575,174.661,5090,4973,2304,2186,0,0,13,0,13,0,56033,65593,2957,3579,1335.00,1055.00,2.00,0.00,996.00,233.00,337.00,822.00,111,125,1876793,1887440,0,0,22979,27115,22979,27115,0,0,6871,8314,152,230,0,7131,368991,193740,103864,96700,15162,17915,110.205,78.781,5894,4929,3797,2295,0,0,0,0,0,0,73554,66748,3859,3572,1058.50,1005.00,0.00,0.00,416.00,227.00,642.50,778.00,128,126,2148677,2142646,0,0,26930,26812,26930,26812,0,0,8321,8806,176,218,0,18288,370541,405453,78309,129640,16167,27257,211.811,396.221,4852,5869,2843,3234,0,0,28,0,28,0,48102,80829,2565,4190,1896.00,1690.50,14.00,0.00,1281.00,382.00,601.00,1308.50,124,140,2085732,2327011,4,3,26333,28669,25678,27573,655,1096,8721,8555,174,1142
3,Avilés,55417,61421,271758,234074,86295,84260,0,0,481.46,446.146,4439,2950,1841,1050,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,64,56,489495,402073,0,0,0,0,0,0,0,0,0,0,0,0,72394,29158,223174,168150,83122,70654,0,0,634.812,505.321,3272,2441,1043,737,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,58,54,448131,463485,0,0,0,0,0,0,0,0,0,0,0,0,56189,55801,244437,140166,128771,139425,0,0,1056.976,1300.444,5070,3727,1377,1609,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,70,66,554362,521111,0,0,0,0,0,0,0,0,0,0,0,0,45014,74314,227675,249775,71541,102711,0,0,2012.55,1504.075,3245,3373,787,753,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,62,70,482399,579821,0,0,0,0,0,0,0,0,0,0,0,0
4,Bahía de Algeciras,2380167,2793935,31659,42904,5747425,5498543,4544515,4436836,85.45,87.537,289720,347997,274832,330817,261841,325168,5067101,5388705,4047780,3990822,1198464,1053639,40107,43612,377600.00,372081.00,312435.00,314846.00,0.00,0.00,65165.00,57235.00,2341,2510,42389630,48344664,0,0,315529,362082,315529,362082,0,0,66691,81135,235,327,1898017,2444604,35205,23432,5293601,5828377,4055921,4746479,26.18,72.429,189284,293342,176700,279798,193570,303375,4802903,5304257,3572655,4221136,1227186,1091761,40301,46610,341186.00,403255.00,284207.00,333981.00,4.00,0.00,56975.00,69274.00,1795,2240,34052082,44702082,0,0,237169,290981,237169,290981,0,0,49402,62103,243,336,2321077,2356131,123376,260,6273346,5890166,4854049,4828568,38.752,40.26,349632,269694,335382,258620,352409,262428,5318723,5229906,4334056,4324863,1413888,1071582,46720,45797,400314.00,396089.00,336648.00,345468.00,4.00,14.00,63662.00,50607.00,2359,2177,45144327,41527204,0,0,312991,316724,312991,316724,0,0,61755,66886,350,340,2359749,2392855,36596,2314,6184103,6202074,4952620,5127554,43.229,108.71,308727,342479,295580,330301,286282,337641,5660961,5657520,4417931,4600562,1221567,1085163,40664,45875,409915.00,412658.00,345933.00,358038.00,0.00,0.00,63982.00,54620.00,2220,2405,41307060,46474631,0,0,327554,346545,327554,346545,0,0,65612,74171,312,385
5,Bahía de Cádiz,163563,18934,137032,206223,166825,173076,115728,119797,839.738,716.423,9651,7914,968,1949,0,0,180514,34356,19199,15766,68949,68593,2039,2237,15875.25,16251.75,1619.50,1569.00,12771.75,12192.75,1484.00,2490.00,142,135,2649740,2451804,13,12,33613,33168,1751,1817,31862,31351,1078,1102,1314,1224,148050,22127,162994,144490,155382,176729,108758,124104,703.2,727.987,6172,8974,2618,5546,0,0,156309,31009,15018,15873,63839,65099,1910,2112,14367.75,16321.25,1436.00,1286.25,10917.25,12885.50,2014.50,2149.50,95,93,2214488,1751712,14,5,20845,12721,1426,1510,19419,11211,846,917,2377,1759,140155,77604,148365,110024,189757,200326,130404,139493,1050.968,844.239,10305,7514,2609,1272,0,0,150417,95191,18815,17587,76923,71437,2328,2263,17027.00,19319.75,1638.25,1849.75,13047.50,14599.00,2341.25,2871.00,123,94,2591176,1808262,16,14,24850,21071,1292,1478,23558,19593,771,929,1789,1285,50715,42600,139223,152369,161301,195263,113089,138220,1011.52,1106.938,6157,7196,2888,1906,0,0,74211,65475,19012,22196,62151,69951,1931,2279,14077.50,18096.25,1638.25,1872.50,10507.00,13384.75,1932.25,2839.00,129,128,3921621,3987028,51,40,65643,64693,1690,2601,63953,62092,1044,1643,1389,9836
6,Baleares,71491,102646,43279,22156,884058,982074,21952,21043,60.77,79.737,2766,6597,138,155,36,105,634,704,0,0,875930,970723,41066,45154,6126.00,6047.00,0.00,0.00,6124.00,6047.00,2.00,0.00,2553,3052,17315621,17177306,16,15,286458,300476,229888,244370,56570,56106,53451,54605,5525,7841,81764,79818,41212,41626,993895,1105893,23743,25170,102.359,83.833,3295,6033,121,61,663,183,918,957,0,0,987844,1095902,46496,51089,6568.00,6709.00,0.00,0.00,6568.00,6709.00,0.00,0.00,2415,2698,15139445,15976850,11,11,266579,292439,220283,247122,46296,45317,43672,54264,6570,11032,68656,126825,23303,16916,1271413,1195038,30084,28429,112.903,142.471,5410,5877,127,217,488,251,1122,884,0,0,1264556,1183433,60671,54892,8332.00,6801.00,0.00,0.00,8332.00,6801.00,0.00,0.00,2836,3056,17401718,18816258,17,19,383131,432348,327390,368670,55741,63678,64703,85251,13670,12338,93106,111202,31421,35730,1195478,1340891,27975,25398,116.885,188.376,10956,10488,146,11,535,421,997,1300,2,0,1182038,1336651,56023,62871,7800.00,7000.00,2.00,0.00,7798.00,6998.00,0.00,2.00,3730,3712,20759717,22128121,58,71,722105,665225,586589,515411,135516,149814,111964,102757,10089,13369
7,Barcelona,989889,766073,413626,324206,3571017,3843295,2789637,3011767,44.076,150.208,118021,112974,103451,100189,0,0,1766323,1989352,1400632,1705002,796861,841346,28411,29940,270816.00,295527.75,116010.00,142352.00,64366.50,69397.25,90439.50,83778.50,644,642,24547383,25184951,26,24,163259,179890,70246,68854,93013,111036,21954,22448,47534,49721,1070862,1012582,369020,362565,3354053,4046216,2522048,3148202,106.389,95.307,106638,93635,92490,82509,0,0,1434073,2177589,1070085,1740316,856022,941276,29291,33374,243685.00,308120.50,91665.50,150334.00,67719.50,74314.00,84300.00,83472.50,601,601,22613490,22939488,20,14,135929,132848,56735,57909,79194,74939,17067,18146,72364,60872,1166042,1189649,499576,396163,3794903,4563660,2745140,3550731,169.035,211.547,116022,102324,97442,82699,0,0,1626892,2561161,1219856,1907463,1089051,1017725,38690,36306,259357.25,348007.00,94237.50,158349.50,80501.75,85211.00,84618.00,104438.50,701,698,26863389,26767254,32,27,216019,254704,96134,121203,119885,133501,23272,29316,77057,74032,1368012,1042996,352117,314063,3616465,4453149,2675116,3429166,108.168,235.408,147345,149131,122363,126503,0,0,1735684,2290086,1261030,1839056,965941,1015506,34219,37159,252905.00,338986.25,101291.50,170591.00,67899.50,82935.25,83714.00,85460.00,720,701,30541700,30767991,79,79,400530,395390,133110,117819,267420,277571,33502,30677,69834,61709
8,Bilbao,1503473,2134486,334672,280264,595059,569573,407988,400193,0,0,9409,9333,4986,4853,0,0,1140,4973,1140,4973,73514,46098,2922,1509,40514.00,36914.00,100.75,394.75,4155.25,1259.50,36258.00,35259.75,195,197,3554616,4149021,0,0,2776,13,2776,13,0,0,1088,0,1530,2377,1505199,1467586,278019,264448,632124,558084,444749,377957,0,0,9555,9196,5063,4873,0,0,4190,5253,4190,5253,76505,59553,3064,975,43415.25,33878.00,246.75,418.00,3868.50,1751.25,39300.00,31708.75,198,169,3632415,3142295,0,0,2208,36,2208,36,0,0,804,0,3086,1327,1801755,2114003,378813,292386,694522,777691,426316,456400,0,0,10954,12351,5696,6546,0,0,2212,2239,1791,2239,81483,88992,3156,2068,39909.00,42956.50,166.25,154.75,3993.00,1782.00,35749.75,41019.75,228,227,4271152,4423032,0,0,3883,0,3883,0,0,0,1662,0,7606,1719,1697306,1896200,300970,416388,774441,749547,457699,425341,0,0,11146,13330,5796,6932,0,0,9574,18228,9574,18228,94966,126292,3597,4687,42999.75,36287.00,513.75,1158.00,3016.25,1570.75,39469.75,33558.25,233,244,5272104,5608259,7,6,18704,31118,11409,11962,7295,19156,4966,5773,14822,27137
9,Cartagena,2345886,2137657,870622,878956,70850,57119,38339,39115,8.327,25.364,9374,12108,770,791,0,0,303101,74172,0,0,1539,0,0,0,2841.75,2791.00,0.00,0.00,624.00,586.00,2217.75,2205.00,154,158,3738345,2985661,5,0,7108,0,0,0,7108,0,0,0,11,0,2106262,2638793,557493,740289,64086,60072,47032,36486,7.779,31.814,12075,12528,892,1329,0,0,0,6314,0,0,2262,0,0,0,3292.75,2814.00,0.00,0.00,640.00,783.00,2652.75,2031.00,144,158,3305512,3454693,3,0,5382,0,0,0,5382,0,0,0,0,4,2605078,2030458,689649,652451,104283,81372,50466,59838,21.022,10.537,20756,13115,1067,739,0,0,77539,2460,29,0,3507,2460,0,0,3386.25,5298.00,2.00,0.00,561.00,1335.00,2823.25,3963.00,177,158,3930557,3403804,4,4,4401,5094,0,0,4401,5094,0,0,0,2002,2794322,2357400,629526,647973,70812,95921,48104,52645,34.21,26.678,21267,20411,1144,930,0,0,0,1916,0,0,3355,0,0,0,4206.50,5318.00,0.00,0.00,1432.25,1772.00,2774.25,3546.00,202,203,4806803,4765533,21,26,17919,21955,0,0,17919,21955,0,0,24,4
10,Castellón,672781,607958,637990,374630,85980,67083,81295,65781,74.793,270.338,2547,2223,0,0,0,0,884,103,884,103,12408,6149,6,0,5675.00,4827.25,199.00,10.00,329.00,408.50,5147.00,4408.75,113,95,1522611,1245576,0,0,0,0,0,0,0,0,0,0,83,29,732854,769242,406445,455495,88478,83689,82007,79476,279.389,321.94,2086,2198,0,0,0,0,1405,2837,1405,2837,12932,5621,3,0,5833.00,5425.00,124.00,140.00,335.00,570.25,5374.00,4714.75,101,108,1425735,1536446,0,0,0,0,0,0,0,0,0,0,96,26,751441,818476,656447,613625,113933,94405,100561,93199,212.056,224.823,2122,2107,0,0,0,0,255,6871,255,2871,11239,5534,8,0,6220.00,6859.00,92.00,146.00,468.00,688.00,5660.00,6025.00,117,107,1634468,1646304,0,0,0,0,0,0,0,0,0,0,62,22,1068669,744729,515772,799387,119760,83019,114425,82071,241.399,99.509,2013,3034,0,0,0,0,1898,66,1898,66,25047,0,0,0,9313.00,5634.25,381.00,8.00,980.00,711.25,7952.00,4915.00,123,122,1860360,1771209,0,1,0,743,0,0,0,743,0,0,204,102
11,Ceuta,51759,72593,1400,0,39391,47621,5644,6528,0.37,0,52984,57034,51436,54981,0,0,0,0,0,0,39001,46545,2308,2676,476.50,487.00,0.00,0.00,459.50,469.00,17.00,18.00,835,860,6232840,6046366,2,0,137760,134862,134655,134862,3105,0,32603,33936,118,171,49966,19340,1000,0,40669,47190,4791,5765,0.138,0,48607,19842,47540,18371,0,0,0,0,0,0,40409,46670,2428,2904,414.00,464.00,0.00,0.00,395.00,436.00,19.00,28.00,674,727,4981338,4245459,2,0,101377,112354,97972,112354,3405,0,22761,27699,105,118,53938,46962,0,1400,50002,42234,6430,5397,0,0,62899,31327,61181,29399,0,0,0,0,0,0,49352,41974,2939,2525,540.00,433.00,0.00,0.00,530.00,422.00,10.00,11.00,843,812,6480239,5225229,4,0,146382,141964,139069,141964,7313,0,31187,33695,128,306,91102,21761,1426,26,38098,46670,4962,5792,0.453,0,39911,46627,37723,44595,0,0,0,0,0,0,37837,45955,2156,2740,402.00,457.00,0.00,0.00,393.00,439.00,9.00,18.00,787,831,5596153,7304888,3,1,148305,143082,142485,142968,5820,114,33978,36246,94,137

In [38]:
df_final_2 = df_final_2.drop(28,axis=0)

In [39]:
df_final_2

,Autoridad Portuaria,Enero_2023 t Graneles Líquidos,Enero_2024 t Graneles Líquidos,Enero_2023 t Graneles Sólidos,Enero_2024 t Graneles Sólidos,Enero_2023 t Mercancía General,Enero_2024 t Mercancía General,Enero_2023 t Mercancía General Contenedores,Enero_2024 t Mercancía General Contenedores,Enero_2023 t Pesca,Enero_2024 t Pesca,Enero_2023 t Avituallamiento,Enero_2024 t Avituallamiento,Enero_2023 t Avituallamiento De Combustibles Líquidos,Enero_2024 t Avituallamiento De Combustibles Líquidos,Enero_2023 t Tráfico Interior,Enero_2024 t Tráfico Interior,Enero_2023 t Mercancías En Tránsito,Enero_2024 t Mercancías En Tránsito,Enero_2023 t Mercancías En Tránsito En Contenedores,Enero_2024 t Mercancías En Tránsito En Contenedores,Enero_2023 t Tráfico Ro-Ro,Enero_2024 t Tráfico Ro-Ro,Enero_2023 UTIS Ro-Ro,Enero_2024 UTIS Ro-Ro,Enero_2023 TEUS Contenedores,Enero_2024 TEUS Contenedores,Enero_2023 TEUS Contenedores En Tránsito,Enero_2024 TEUS Contenedores En Tránsito,Enero_2023 TEUS Contenedores Entrada-Salida Nacional,Enero_2024 TEUS Contenedores Entrada-Salida Nacional,Enero_2023 TEUS Contenedores Entrada-Salida Exterior,Enero_2024 TEUS Contenedores Entrada-Salida Exterior,Enero_2023 Unidades Buques Mercantes,Enero_2024 Unidades Buques Mercantes,Enero_2023 G.T. Buques Mercantes,Enero_2024 G.T. Buques Mercantes,Enero_2023 Unidades Buques De Crucero,Enero_2024 Unidades Buques De Crucero,Enero_2023 Pasajeros En Régimen De Transporte Y De Crucero,Enero_2024 Pasajeros En Régimen De Transporte Y De Crucero,Enero_2023 Pasajeros En Régimen De Transporte,Enero_2024 Pasajeros En Régimen De Transporte,Enero_2023 Pasajeros De Crucero,Enero_2024 Pasajeros De Crucero,Enero_2023 Automóviles En Régimen De Pasaje,Enero_2024 Automóviles En Régimen De Pasaje,Enero_2023 Automóviles En Régimen De Mercancía,Enero_2024 Automóviles En Régimen De Mercancía,Febrero_2023 t Graneles Líquidos,Febrero_2024 t Graneles Líquidos,Febrero_2023 t Graneles Sólidos,Febrero_2024 t Graneles Sólidos,Febrero Mercancía General,Febrero_2024 t Mercancía General,Febrero_2023 t Mercancía General Contenedores,Febrero_2024 t Mercancía General Contenedores,Febrero_2023 t Pesca,Febrero_2024 t Pesca,Febrero_2023 t Avituallamiento,Febrero_2024 t Avituallamiento,Febrero_2023 t Avituallamiento De Combustibles Líquidos,Febrero_2024 t Avituallamiento De Combustibles Líquidos,Febrero_2023 t Tráfico Interior,Febrero_2024 t Tráfico Interior,Febrero_2023 t Mercancías En Tránsito,Febrero_2024 t Mercancías En Tránsito,Febrero_2023 t Mercancías En Tránsito En Contenedores,Febrero_2024 t Mercancías En Tránsito En Contenedores,Febrero_2023 t Tráfico Ro-Ro,Febrero_2024 t Tráfico Ro-Ro,Febrero Unidades de transporte intermodal Ro-Ro UTIS,Febrero_2024 UTIS Ro-Ro,Febrero_2023 TEUS Contenedores,Febrero_2024 TEUS Contenedores,Febrero_2023 TEUS Contenedores En Tránsito,Febrero_2024 TEUS Contenedores En Tránsito,Febrero_2023 TEUS Contenedores Entrada-Salida Nacional,Febrero_2024 TEUS Contenedores Entrada-Salida Nacional,Febrero_2023 TEUS Contenedores Entrada-Salida Exterior,Febrero_2024 TEUS Contenedores Entrada-Salida Exterior,Febrero_2023 Unidades Buques Mercantes,Febrero_2024 Unidades Buques Mercantes,Febrero_2023 G.T. Buques Mercantes,Febrero_2024 G.T. Buques Mercantes,Febrero_2023 Unidades Buques De Crucero,Febrero_2024 Unidades Buques De Crucero,Febrero_2023 Pasajeros En Régimen De Transporte Y De Crucero,Febrero_2024 Pasajeros En Régimen De Transporte Y De Crucero,Febrero_2023 Pasajeros En Régimen De Transporte,Febrero_2024 Pasajeros En Régimen De Transporte,Febrero_2023 Pasajeros De Crucero,Febrero_2024 Pasajeros De Crucero,Febrero_2023 Automóviles En Régimen De Pasaje,Febrero_2024 Automóviles En Régimen De Pasaje,Febrero_2023 Automóviles En Régimen De Mercancía,Febrero_2024 Automóviles En Régimen De Mercancía,Marzo_2023 t Graneles Líquidos,Marzo_2024 t Graneles Líquidos,Marzo Graneles Sólidos,Marzo_2024 t Graneles Sólidos,Marzo_2023 t Mercancía General,Marzo_2024 t Mercancía General,Marzo_2023 t Mercancía General Contenedores,Marzo_2024 t Mercancía General Contenedores,Marzo_2023 t Pesca,Marzo_2024 t Pesca,Marzo_2023 t Avituallamiento,Marzo_2024 t Avituallamiento,Marzo_2023 t Avituallamiento De Combustibles Líquidos,Marzo_2024 t Avituallamiento De Combustibles Líquidos,Marzo_2023 t Tráfico Interior,Marzo_2024 t Tráfico Interior,Marzo_2023 t Mercancías En Tránsito,Marzo_2024 t Mercancías En Tránsito,Marzo_2023 t Mercancías En Tránsito En Contenedores,Marzo_2024 t Mercancías En Tránsito En Contenedores,Marzo_2023 t Tráfico Ro-Ro,Marzo_2024 t Tráfico Ro-Ro,Marzo_2023 UTIS Ro-Ro,Marzo_2024 UTIS Ro-Ro,Marzo_2023 TEUS Contenedores,Marzo_2024 TEUS Contenedores,Marzo_2023 TEUS Contenedores En Tránsito,Marzo_2024 TEUS Contenedores En Tránsito,Marzo_2023 TEUS Contenedores Entrada-Salida Nacional,Marzo_2024 TEUS Contenedores Entrada-Salida Nacional,Marzo_2023 TEUS Contenedores Entrada-Salida Exterior,Marzo_2024 TEUS Contenedores Entrada-Salida Exterior,Marzo_2023 Unidades Buques Mercantes,Marzo_2024 Unidades Buques Mercantes,Marzo_2023 G.T. Buques Mercantes,Marzo_2024 G.T. Buques Mercantes,Marzo_2023 Unidades Buques De Crucero,Marzo_2024 Unidades Buques De Crucero,Marzo_2023 Pasajeros En Régimen De Transporte Y De Crucero,Marzo_2024 Pasajeros En Régimen De Transporte Y De Crucero,Marzo_2023 Pasajeros En Régimen De Transporte,Marzo_2024 Pasajeros En Régimen De Transporte,Marzo_2023 Pasajeros De Crucero,Marzo_2024 Pasajeros De Crucero,Marzo_2023 Automóviles En Régimen De Pasaje,Marzo_2024 Automóviles En Régimen De Pasaje,Marzo_2023 Automóviles En Régimen De Mercancía,Marzo_2024 Automóviles En Régimen De Mercancía,Abril_2023 t Graneles Líquidos,Abril_2024 t Graneles Líquidos,Abril_2023 t Graneles Sólidos,Abril_2024 t Graneles Sólidos,Abril_2023 t Mercancía General,Abril_2024 t Mercancía General,Abril_2023 t Mercancía General Contenedores,Abril_2024 t Mercancía General Contenedores,Abril_2023 t Pesca,Abril_2024 t Pesca,Abril_2023 t Avituallamiento,Abril_2024 t Avituallamiento,Abril_2023 t Avituallamiento De Combustibles Líquidos,Abril_2024 t Avituallamiento De Combustibles Líquidos,Abril_2023 t Tráfico Interior,Abril_2024 t Tráfico Interior,Abril_2023 t Mercancías En Tránsito,Abril_2024 t Mercancías En Tránsito,Abril_2023 t Mercancías En Tránsito En Contenedores,Abril_2024 t Mercancías En Tránsito En Contenedores,Abril_2023 t Tráfico Ro-Ro,Abril_2024 t Tráfico Ro-Ro,Abril_2023 UTIS Ro-Ro,Abril_2024 UTIS Ro-Ro,Abril_2023 TEUS Contenedores,Abril_2024 TEUS Contenedores,Abril_2023 TEUS Contenedores En Tránsito,Abril_2024 TEUS Contenedores En Tránsito,Abril_2023 TEUS Contenedores Entrada-Salida Nacional,Abril_2024 TEUS Contenedores Entrada-Salida Nacional,Abril_2023 TEUS Contenedores Entrada-Salida Exterior,Abril_2024 TEUS Contenedores Entrada-Salida Exterior,Abril_2023 Unidades Buques Mercantes,Abril_2024 Unidades Buques Mercantes,Abril_2023 G.T. Buques Mercantes,Abril_2024 G.T. Buques Mercantes,Abril_2023 Unidades Buques De Crucero,Abril_2024 Unidades Buques De Crucero,Abril_2023 Pasajeros En Régimen De Transporte Y De Crucero,Abril_2024 Pasajeros En Régimen De Transporte Y De Crucero,Abril_2023 Pasajeros En Régimen De Transporte,Abril_2024 Pasajeros En Régimen De Transporte,Abril_2023 Pasajeros De Crucero,Abril_2024 Pasajeros De Crucero,Abril_2023 Automóviles En Régimen De Pasaje,Abril_2024 Automóviles En Régimen De Pasaje,Abril_2023 Automóviles En Régimen De Mercancía,Abril_2024 Automóviles En Régimen De Mercancía
0,A Coruña,676655,719906,521447,406133,40997,29789,66,0,1202.998,1148.912,2027,2903,1488,2245,0,0,268394,41024,0,0,0,0,0,0,6.00,0.00,0.00,0.00,0.00,0.00,6.00,0.00,81,81,1458841,1556239,4,4,6584,9704,0,0,6584,9704,0,0,0,0,895370,747204,542383,288615,57323,14295,0,0,1385.374,1002.014,3713,2130,2599,1310,0,0,315786,7917,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,96,70,1545849,1185147,0,2,0,3714,0,0,0,3714,0,0,0,0,591403,863302,544458,279003,80350,50451,0,0,2442.947,1445.893,7792,7032,3394,2081,0,0,318609,7920,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,86,98,1659967,1843269,4,5,10565,13679,0,0,10565,13679,0,0,0,0,548746,1021334,482784,439120,56369,77264,43,14,2122.334,1716.183,3001,2996,2239,2034,0,0,172519,98438,0,0,0,0,0,0,3.00,2.00,0.00,0.00,0.00,0.00,3.00,2.00,103,119,2292395,3316704,14,16,27030,47166,0,0,27030,47166,0,0,0,0
1,Alicante,5453,9007,191759,109123,96205,86149,89346,77281,0,0,1864,881,183,55,0,0,1100,297,1100,297,4830,6210,186,232,14253.75,10654.75,109.50,38.00,11790.50,8703.50,2353.75,1913.25,58,54,977692,548180,4,1,20175,8151,9362,5990,10813,2161,2517,1580,78,51,0,1848,135408,175579,96732,92710,89634,89152,0,0,1447,2312,186,102,0,0,0,580,0,580,51,907,0,0,13856.75,14240.75,0.00,56.00,11734.50,12023.50,2122.25,2161.25,53,55,816249,664578,4,0,18333,11828,8555,11828,9778,0,1938,4102,142,241,6504,9103,276103,220934,107639,110251,96319,105093,0,0,1509,1554,204,79,0,0,0,1901,0,1901,4804,406,214,5,14534.00,16216.50,0.00,203.00,13380.25,13920.50,1153.75,2093.00,57,67,745037,857634,3,2,13212,9669,7243,7215,5969,2454,1687,3133,95,243,1,2188,115313,193671,95672,87769,92492,84155,0,0,2751,1656,123,181,0,0,3908,1901,3908,1901,228,1604,0,0,13645.25,13062.75,437.50,203.00,11838.00,11700.25,1369.75,1159.50,56,70,1042086,2089152,9,17,23635,40447,11055,8181,12580,32266,3120,3197,117,228
2,Almería,4538,18511,299084,256126,74717,109347,11672,15607,186.172,228.505,5207,6088,2983,2622,0,0,2,0,2,0,49520,63344,2493,3102,1293.50,1116.75,1.00,0.00,746.00,457.75,546.50,659.00,112,134,1897714,2131887,0,0,35434,40825,35434,40825,0,0,9707,11445,170,239,3689,19338,313763,256103,97314,116222,9285,18881,145.575,174.661,5090,4973,2304,2186,0,0,13,0,13,0,56033,65593,2957,3579,1335.00,1055.00,2.00,0.00,996.00,233.00,337.00,822.00,111,125,1876793,1887440,0,0,22979,27115,22979,27115,0,0,6871,8314,152,230,0,7131,368991,193740,103864,96700,15162,17915,110.205,78.781,5894,4929,3797,2295,0,0,0,0,0,0,73554,66748,3859,3572,1058.50,1005.00,0.00,0.00,416.00,227.00,642.50,778.00,128,126,2148677,2142646,0,0,26930,26812,26930,26812,0,0,8321,8806,176,218,0,18288,370541,405453,78309,129640,16167,27257,211.811,396.221,4852,5869,2843,3234,0,0,28,0,28,0,48102,80829,2565,4190,1896.00,1690.50,14.00,0.00,1281.00,382.00,601.00,1308.50,124,140,2085732,2327011,4,3,26333,28669,25678,27573,655,1096,8721,8555,174,1142
3,Avilés,55417,61421,271758,234074,86295,84260,0,0,481.46,446.146,4439,2950,1841,1050,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,64,56,489495,402073,0,0,0,0,0,0,0,0,0,0,0,0,72394,29158,223174,168150,83122,70654,0,0,634.812,505.321,3272,2441,1043,737,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,58,54,448131,463485,0,0,0,0,0,0,0,0,0,0,0,0,56189,55801,244437,140166,128771,139425,0,0,1056.976,1300.444,5070,3727,1377,1609,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,70,66,554362,521111,0,0,0,0,0,0,0,0,0,0,0,0,45014,74314,227675,249775,71541,102711,0,0,2012.55,1504.075,3245,3373,787,753,0,0,0,0,0,0,0,0,0,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,62,70,482399,579821,0,0,0,0,0,0,0,0,0,0,0,0
4,Bahía de Algeciras,2380167,2793935,31659,42904,5747425,5498543,4544515,4436836,85.45,87.537,289720,347997,274832,330817,261841,325168,5067101,5388705,4047780,3990822,1198464,1053639,40107,43612,377600.00,372081.00,312435.00,314846.00,0.00,0.00,65165.00,57235.00,2341,2510,42389630,48344664,0,0,315529,362082,315529,362082,0,0,66691,81135,235,327,1898017,2444604,35205,23432,5293601,5828377,4055921,4746479,26.18,72.429,189284,293342,176700,279798,193570,303375,4802903,5304257,3572655,4221136,1227186,1091761,40301,46610,341186.00,403255.00,284207.00,333981.00,4.00,0.00,56975.00,69274.00,1795,2240,34052082,44702082,0,0,237169,290981,237169,290981,0,0,49402,62103,243,336,2321077,2356131,123376,260,6273346,5890166,4854049,4828568,38.752,40.26,349632,269694,335382,258620,352409,262428,5318723,5229906,4334056,4324863,1413888,1071582,46720,45797,400314.00,396089.00,336648.00,345468.00,4.00,14.00,63662.00,50607.00,2359,2177,45144327,41527204,0,0,312991,316724,312991,316724,0,0,61755,66886,350,340,2359749,2392855,36596,2314,6184103,6202074,4952620,5127554,43.229,108.71,308727,342479,295580,330301,286282,337641,5660961,5657520,4417931,4600562,1221567,1085163,40664,45875,409915.00,412658.00,345933.00,358038.00,0.00,0.00,63982.00,54620.00,2220,2405,41307060,46474631,0,0,327554,346545,327554,346545,0,0,65612,74171,312,385
5,Bahía de Cádiz,163563,18934,137032,206223,166825,173076,115728,119797,839.738,716.423,9651,7914,968,1949,0,0,180514,34356,19199,15766,68949,68593,2039,2237,15875.25,16251.75,1619.50,1569.00,12771.75,12192.75,1484.00,2490.00,142,135,2649740,2451804,13,12,33613,33168,1751,1817,31862,31351,1078,1102,1314,1224,148050,22127,162994,144490,155382,176729,108758,124104,703.2,727.987,6172,8974,2618,5546,0,0,156309,31009,15018,15873,63839,65099,1910,2112,14367.75,16321.25,1436.00,1286.25,10917.25,12885.50,2014.50,2149.50,95,93,2214488,1751712,14,5,20845,12721,1426,1510,19419,11211,846,917,2377,1759,140155,77604,148365,110024,189757,200326,130404,139493,1050.968,844.239,10305,7514,2609,1272,0,0,150417,95191,18815,17587,76923,71437,2328,2263,17027.00,19319.75,1638.25,1849.75,13047.50,14599.00,2341.25,2871.00,123,94,2591176,1808262,16,14,24850,21071,1292,1478,23558,19593,771,929,1789,1285,50715,42600,139223,152369,161301,195263,113089,138220,1011.52,1106.938,6157,7196,2888,1906,0,0,74211,65475,19012,22196,62151,69951,1931,2279,14077.50,18096.25,1638.25,1872.50,10507.00,13384.75,1932.25,2839.00,129,128,3921621,3987028,51,40,65643,64693,1690,2601,63953,62092,1044,1643,1389,9836
6,Baleares,71491,102646,43279,22156,884058,982074,21952,21043,60.77,79.737,2766,6597,138,155,36,105,634,704,0,0,875930,970723,41066,45154,6126.00,6047.00,0.00,0.00,6124.00,6047.00,2.00,0.00,2553,3052,17315621,17177306,16,15,286458,300476,229888,244370,56570,56106,53451,54605,5525,7841,81764,79818,41212,41626,993895,1105893,23743,25170,102.359,83.833,3295,6033,121,61,663,183,918,957,0,0,987844,1095902,46496,51089,6568.00,6709.00,0.00,0.00,6568.00,6709.00,0.00,0.00,2415,2698,15139445,15976850,11,11,266579,292439,220283,247122,46296,45317,43672,54264,6570,11032,68656,126825,23303,16916,1271413,1195038,30084,28429,112.903,142.471,5410,5877,127,217,488,251,1122,884,0,0,1264556,1183433,60671,54892,8332.00,6801.00,0.00,0.00,8332.00,6801.00,0.00,0.00,2836,3056,17401718,18816258,17,19,383131,432348,327390,368670,55741,63678,64703,85251,13670,12338,93106,111202,31421,35730,1195478,1340891,27975,25398,116.885,188.376,10956,10488,146,11,535,421,997,1300,2,0,1182038,1336651,56023,62871,7800.00,7000.00,2.00,0.00,7798.00,6998.00,0.00,2.00,3730,3712,20759717,22128121,58,71,722105,665225,586589,515411,135516,149814,111964,102757,10089,13369
7,Barcelona,989889,766073,413626,324206,3571017,3843295,2789637,3011767,44.076,150.208,118021,112974,103451,100189,0,0,1766323,1989352,1400632,1705002,796861,841346,28411,29940,270816.00,295527.75,116010.00,142352.00,64366.50,69397.25,90439.50,83778.50,644,642,24547383,25184951,26,24,163259,179890,70246,68854,93013,111036,21954,22448,47534,49721,1070862,1012582,369020,362565,3354053,4046216,2522048,3148202,106.389,95.307,106638,93635,92490,82509,0,0,1434073,2177589,1070085,1740316,856022,941276,29291,33374,243685.00,308120.50,91665.50,150334.00,67719.50,74314.00,84300.00,83472.50,601,601,22613490,22939488,20,14,135929,132848,56735,57909,79194,74939,17067,18146,72364,60872,1166042,1189649,499576,396163,3794903,4563660,2745140,3550731,169.035,211.547,116022,102324,97442,82699,0,0,1626892,2561161,1219856,1907463,1089051,1017725,38690,36306,259357.25,348007.00,94237.50,158349.50,80501.75,85211.00,84618.00,104438.50,701,698,26863389,26767254,32,27,216019,254704,96134,121203,119885,133501,23272,29316,77057,74032,1368012,1042996,352117,314063,3616465,4453149,2675116,3429166,108.168,235.408,147345,149131,122363,126503,0,0,1735684,2290086,1261030,1839056,965941,1015506,34219,37159,252905.00,338986.25,101291.50,170591.00,67899.50,82935.25,83714.00,85460.00,720,701,30541700,30767991,79,79,400530,395390,133110,117819,267420,277571,33502,30677,69834,61709
8,Bilbao,1503473,2134486,334672,280264,595059,569573,407988,400193,0,0,9409,9333,4986,4853,0,0,1140,4973,1140,4973,73514,46098,2922,1509,40514.00,36914.00,100.75,394.75,4155.25,1259.50,36258.00,35259.75,195,197,3554616,4149021,0,0,2776,13,2776,13,0,0,1088,0,1530,2377,1505199,1467586,278019,264448,632124,558084,444749,377957,0,0,9555,9196,5063,4873,0,0,4190,5253,4190,5253,76505,59553,3064,975,43415.25,33878.00,246.75,418.00,3868.50,1751.25,39300.00,31708.75,198,169,3632415,3142295,0,0,2208,36,2208,36,0,0,804,0,3086,1327,1801755,2114003,378813,292386,694522,777691,426316,456400,0,0,10954,12351,5696,6546,0,0,2212,2239,1791,2239,81483,88992,3156,2068,39909.00,42956.50,166.25,154.75,3993.00,1782.00,35749.75,41019.75,228,227,4271152,4423032,0,0,3883,0,3883,0,0,0,1662,0,7606,1719,1697306,1896200,300970,416388,774441,749547,457699,425341,0,0,11146,13330,5796,6932,0,0,9574,18228,9574,18228,94966,126292,3597,4687,42999.75,36287.00,513.75,1158.00,3016.25,1570.75,39469.75,33558.25,233,244,5272104,5608259,7,6,18704,31118,11409,11962,7295,19156,4966,5773,14822,27137
9,Cartagena,2345886,2137657,870622,878956,70850,57119,38339,39115,8.327,25.364,9374,12108,770,791,0,0,303101,74172,0,0,1539,0,0,0,2841.75,2791.00,0.00,0.00,624.00,586.00,2217.75,2205.00,154,158,3738345,2985661,5,0,7108,0,0,0,7108,0,0,0,11,0,2106262,2638793,557493,740289,64086,60072,47032,36486,7.779,31.814,12075,12528,892,1329,0,0,0,6314,0,0,2262,0,0,0,3292.75,2814.00,0.00,0.00,640.00,783.00,2652.75,2031.00,144,158,3305512,3454693,3,0,5382,0,0,0,5382,0,0,0,0,4,2605078,2030458,689649,652451,104283,81372,50466,59838,21.022,10.537,20756,13115,1067,739,0,0,77539,2460,29,0,3507,2460,0,0,3386.25,5298.00,2.00,0.00,561.00,1335.00,2823.25,3963.00,177,158,3930557,3403804,4,4,4401,5094,0,0,4401,5094,0,0,0,2002,2794322,2357400,629526,647973,70812,95921,48104,52645,34.21,26.678,21267,20411,1144,930,0,0,0,1916,0,0,3355,0,0,0,4206.50,5318.00,0.00,0.00,1432.25,1772.00,2774.25,3546.00,202,203,4806803,4765533,21,26,17919,21955,0,0,17919,21955,0,0,24,4
10,Castellón,672781,607958,637990,374630,85980,67083,81295,65781,74.793,270.338,2547,2223,0,0,0,0,884,103,884,103,12408,6149,6,0,5675.00,4827.25,199.00,10.00,329.00,408.50,5147.00,4408.75,113,95,1522611,1245576,0,0,0,0,0,0,0,0,0,0,83,29,732854,769242,406445,455495,88478,83689,82007,79476,279.389,321.94,2086,2198,0,0,0,0,1405,2837,1405,2837,12932,5621,3,0,5833.00,5425.00,124.00,140.00,335.00,570.25,5374.00,4714.75,101,108,1425735,1536446,0,0,0,0,0,0,0,0,0,0,96,26,751441,818476,656447,613625,113933,94405,100561,93199,212.056,224.823,2122,2107,0,0,0,0,255,6871,255,2871,11239,5534,8,0,6220.00,6859.00,92.00,146.00,468.00,688.00,5660.00,6025.00,117,107,1634468,1646304,0,0,0,0,0,0,0,0,0,0,62,22,1068669,744729,515772,799387,119760,83019,114425,82071,241.399,99.509,2013,3034,0,0,0,0,1898,66,1898,66,25047,0,0,0,9313.00,5634.25,381.00,8.00,980.00,711.25,7952.00,4915.00,123,122,1860360,1771209,0,1,0,743,0,0,0,743,0,0,204,102
11,Ceuta,51759,72593,1400,0,39391,47621,5644,6528,0.37,0,52984,57034,51436,54981,0,0,0,0,0,0,39001,46545,2308,2676,476.50,487.00,0.00,0.00,459.50,469.00,17.00,18.00,835,860,6232840,6046366,2,0,137760,134862,134655,134862,3105,0,32603,33936,118,171,49966,19340,1000,0,40669,47190,4791,5765,0.138,0,48607,19842,47540,18371,0,0,0,0,0,0,40409,46670,2428,2904,414.00,464.00,0.00,0.00,395.00,436.00,19.00,28.00,674,727,4981338,4245459,2,0,101377,112354,97972,112354,3405,0,22761,27699,105,118,53938,46962,0,1400,50002,42234,6430,5397,0,0,62899,31327,61181,29399,0,0,0,0,0,0,49352,41974,2939,2525,540.00,433.00,0.00,0.00,530.00,422.00,10.00,11.00,843,812,6480239,5225229,4,0,146382,141964,139069,141964,7313,0,31187,33695,128,306,91102,21761,1426,26,38098,46670,4962,5792,0.453,0,39911,46627,37723,44595,0,0,0,0,0,0,37837,45955,2156,2740,402.00,457.00,0.00,0.00,393.00,439.00,9.00,18.00,787,831,5596153,7304888,3,1,148305,143082,142485,142968,5820,114,33978,36246,94,137

In [40]:
# Guardar una copia en csv
df_final_2.to_csv('archivos_mineria_funciones_cargo_2024/cargas_2024.csv', encoding='utf-8', sep=';')

In [41]:
import openpyxl
df_final_2.to_excel('archivos_mineria_funciones_cargo_2024/carga_2024.xlsx')